# This file created by conda-build 24.7.1
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Thu Sep  5 18:20:57 2024
# ------------------------------------------------

package:
  name: cffi
  version: 1.17.1
source:
  patches:
    - 0001-Link-to-dl-library.patch
    - 0002-setup-linux.patch
    - 0003-apple-api.patch
  sha256: 1c39c6016c32bc48dd54561950ebd6836e1670f2ae46128f67cf49e789c52824
  url: https://pypi.io/packages/source/c/cffi/cffi-1.17.1.tar.gz
build:
  number: '0'
  script: /Users/runner/miniforge3/conda-bld/cffi_1725560578465/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
    -m pip install . -vv --no-deps --no-build-isolation
  string: py312h0fad829_0
requirements:
  build:
    - bzip2 1.0.8 hfdf4475_7
    - ca-certificates 2024.8.30 h8857fd0_0
    - cctools_osx-64 986 h98e843e_4
    - cctools_osx-arm64 986 h7a13591_4
    - clang 17.0.6 default_he371ed4_7
    - clang-17 17.0.6 default_hb173f14_7
    - clang_impl_osx-arm64 17.0.6 h840ab8d_19
    - clang_osx-arm64 17.0.6 h40be2b1_19
    - clangxx 17.0.6 default_he371ed4_7
    - compiler-rt 17.0.6 h1020d70_2
    - compiler-rt_osx-64 17.0.6 hf2b8a54_2
    - cross-python_osx-arm64 3.12 42_cpython
    - crossenv 1.4.0 pyhd8ed1ab_0
    - gettext 0.22.5 hdfe23c8_3
    - gettext-tools 0.22.5 hdfe23c8_3
    - icu 75.1 h120a0e1_0
    - ld64_osx-64 711 h38c89e5_4
    - ld64_osx-arm64 711 h2b3077e_4
    - libasprintf 0.22.5 hdfe23c8_3
    - libasprintf-devel 0.22.5 hdfe23c8_3
    - libclang-cpp17 17.0.6 default_hb173f14_7
    - libcxx 18.1.8 hd876a4e_7
    - libcxx-devel 17.0.6 h8f8a49f_6
    - libexpat 2.6.2 h73e2aa4_0
    - libffi 3.4.2 h0d85af4_5
    - libgettextpo 0.22.5 hdfe23c8_3
    - libgettextpo-devel 0.22.5 hdfe23c8_3
    - libiconv 1.17 hd75f5a5_2
    - libintl 0.22.5 hdfe23c8_3
    - libintl-devel 0.22.5 hdfe23c8_3
    - libllvm17 17.0.6 hbedff68_1
    - libsqlite 3.46.1 h4b8f8c9_0
    - libxml2 2.12.7 heaf3512_4
    - libzlib 1.3.1 h87427d6_1
    - llvm-tools 17.0.6 hbedff68_1
    - lz4-c 1.9.4 hf0c8a7f_0
    - macosx_deployment_target_osx-arm64 11.0 h6553868_1
    - ncurses 6.5 hf036a51_1
    - openssl 3.3.2 hd23fc13_0
    - patch 2.7.6 hbcf498f_1002
    - popt 1.16 h7b079dc_2002
    - python 3.12.5 h37a9e06_0_cpython
    - readline 8.2 h9e318b2_1
    - rsync 3.3.0 h5aaac6a_0
    - sed 4.7 h3efe00b_1000
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1300.6.5 h390ca13_0
    - tk 8.6.13 h1abcd95_1
    - tzdata 2024a h8827d51_1
    - xxhash 0.8.2 h4140336_0
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.6 h915ae27_0
  host:
    - bzip2 1.0.8 h99b78c6_7
    - ca-certificates 2024.8.30 hf0a4a13_0
    - libexpat 2.6.2 hebf3989_0
    - libffi 3.4.2 h3422bc3_5
    - libsqlite 3.46.1 hc14010f_0
    - libzlib 1.3.1 hfb2fe0b_1
    - ncurses 6.5 h7bae524_1
    - openssl 3.3.2 h8359307_0
    - pip 24.2 pyh8b19718_1
    - pycparser 2.22 pyhd8ed1ab_0
    - python 3.12.5 h30c5eda_0_cpython
    - readline 8.2 h92ec313_1
    - setuptools 73.0.1 pyhd8ed1ab_0
    - tk 8.6.13 h5083fa2_1
    - tzdata 2024a h8827d51_1
    - wheel 0.44.0 pyhd8ed1ab_0
    - xz 5.2.6 h57fd34a_0
  run:
    - __osx >=11.0
    - libffi >=3.4,<4.0a0
    - pycparser
    - python >=3.12,<3.13.0a0
    - python >=3.12,<3.13.0a0 *_cpython
    - python_abi 3.12.* *_cp312
test:
  commands:
    - pip check
    - python -X faulthandler -c "from cffi import FFI; print(FFI().dlopen(None))"
  imports:
    - _cffi_backend
    - cffi
  requires:
    - openssl *
    - pip
about:
  description: 'Cffi aims to allow users to call C code from Python without having
    to

    learn a 3rd language. It provides a convenient and reliable way to call

    compiled C code from Python using interface declarations written in C.

    '
  dev_url: https://bitbucket.org/cffi/cffi/overview
  doc_source_url: https://bitbucket.org/cffi/cffi/src/default/doc/?at=default
  doc_url: http://cffi.readthedocs.org
  home: https://bitbucket.org/cffi/cffi
  license: MIT
  license_file: LICENSE
  summary: Foreign Function Interface for Python calling C code.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240905.2.1
  recipe-maintainers:
    - goanpeca
    - katietz
    - mingwandroid
    - ocefpaf
  remote_url: https://github.com/conda-forge/cffi-feedstock
  sha: 9691447b974019208e78fde1979ace33568169af
