# This file created by conda-build 24.5.1
# ------------------------------------------------

package:
  name: libsolv
  version: 0.7.30
source:
  fn: libsolv-0.7.30.tar.gz
  patches:
    - conda_variant_priorization.patch
    - no_error_subdir_mismatch.patch
  sha256: ce4aa2f0e3c5c9ab99dced6a1810af3f670f1b98892394edc68ccabe7b272133
  url: https://github.com/openSUSE/libsolv/archive/0.7.30.tar.gz
build:
  number: 0
  run_exports:
    - libsolv >=0.7.30,<0.8.0a0
  string: h6c9b7f8_0
requirements:
  build:
    - bzip2 1.0.8 h10d778d_5
    - c-ares 1.32.1 h51dda26_0
    - ca-certificates 2024.7.4 h8857fd0_0
    - cctools_osx-64 986 ha1c5b94_0
    - cctools_osx-arm64 986 h7bb7a8e_0
    - clang 16.0.6 default_h179603d_9
    - clang-16 16.0.6 default_h0c94c6a_9
    - clang_impl_osx-arm64 16.0.6 ha81d56d_17
    - clang_osx-arm64 16.0.6 h40be2b1_17
    - clangxx 16.0.6 default_h179603d_9
    - clangxx_impl_osx-arm64 16.0.6 h4a79b72_17
    - clangxx_osx-arm64 16.0.6 h40be2b1_17
    - cmake 3.30.0 h749d262_0
    - compiler-rt 16.0.6 ha38d28d_2
    - compiler-rt_osx-64 16.0.6 ha38d28d_2
    - icu 73.2 hf5e326d_0
    - krb5 1.21.3 h37d8d59_0
    - ld64_osx-64 711 ha20a434_0
    - ld64_osx-arm64 711 h6aa3cc8_0
    - libclang-cpp16 16.0.6 default_h0c94c6a_9
    - libcurl 8.8.0 hf9fcc65_1
    - libcxx 18.1.8 hef8daea_0
    - libedit 3.1.20191231 h0678c8f_2
    - libev 4.33 h10d778d_2
    - libexpat 2.6.2 h73e2aa4_0
    - libiconv 1.17 hd75f5a5_2
    - libllvm16 16.0.6 hbedff68_3
    - libnghttp2 1.58.0 h64cf6d3_1
    - libssh2 1.11.0 hd019ec5_0
    - libuv 1.48.0 h67532ce_0
    - libxml2 2.12.7 hc603aa4_3
    - libzlib 1.3.1 h87427d6_1
    - llvm-tools 16.0.6 hbedff68_3
    - macosx_deployment_target_osx-arm64 11.0 h6553868_1
    - ncurses 6.5 h5846eda_0
    - ninja 1.12.1 h3c5361c_0
    - openssl 3.3.1 h87427d6_1
    - rhash 1.4.4 h0dc2134_0
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.6 h915ae27_0
  host:
    - libcxx 18.1.8 h167917d_0
    - libzlib 1.3.1 hfb2fe0b_1
    - zlib 1.3.1 hfb2fe0b_1
  run:
    - __osx >=11.0
    - libcxx >=16
    - libzlib >=1.3.1,<2.0a0
test:
  commands:
    - test -f "${PREFIX}/lib/libsolv${SHLIB_EXT}"
    - test -f "${PREFIX}/lib/libsolvext${SHLIB_EXT}"
    - test -f "${PREFIX}/include/solv/repo.h"
    - dumpsolv -h
    - cmake -G Ninja -S test/ -B build/ -D LIB_NAME="libsolv${SHLIB_EXT}" ${CMAKE_ARGS}
    - cmake --build build/
    - cmake --build build --target test
  files:
    - test/*
  requires:
    - clang_osx-arm64 16.*
    - clangxx_osx-arm64 16.*
    - cmake
    - ninja
about:
  description: libsolv, a free package dependency solver using a satisfiability algorithm.
  dev_url: https://github.com/openSUSE/libsolv
  home: https://github.com/openSUSE/libsolv
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.BSD
  summary: Library for solving packages and reading repositories
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240712.1.1
  recipe-maintainers:
    - AntoinePrv
    - JohanMabille
    - SylvainCorlay
    - adriendelsalle
    - davidbrochart
    - pavelzw
    - wolfv
  remote_url: https://github.com/conda-forge/libsolv-feedstock
  sha: b5ac07fa8c398c9797eb56da6d78c8aed68f1225
