# This file created by conda-build 24.7.1
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Mon Sep  2 18:47:14 2024
# ------------------------------------------------

package:
  name: jsonpointer
  version: 3.0.0
source:
  sha256: 2b2d729f2091522d61c3b31f82e11870f60b68f43fbc705cb76bf4b832af59ef
  url: https://pypi.io/packages/source/j/jsonpointer/jsonpointer-3.0.0.tar.gz
build:
  number: '1'
  script: /Users/runner/miniforge3/conda-bld/jsonpointer_1725302931775/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/python
    -m pip install . -vv
  string: py312h81bd7bf_1
requirements:
  build:
    - bzip2 1.0.8 hfdf4475_7
    - ca-certificates 2024.8.30 h8857fd0_0
    - cctools_osx-64 986 h6e61e4f_3
    - cctools_osx-arm64 986 hffacd06_3
    - clang 18.1.8 default_h179603d_3
    - clang-18 18.1.8 default_h0c94c6a_3
    - clang_impl_osx-arm64 18.1.8 hadf8e89_19
    - clang_osx-arm64 18.1.8 h40be2b1_19
    - clangxx 18.1.8 default_h179603d_3
    - compiler-rt 18.1.8 h1020d70_1
    - compiler-rt_osx-64 18.1.8 hf2b8a54_1
    - cross-python_osx-arm64 3.12 42_cpython
    - crossenv 1.4.0 pyhd8ed1ab_0
    - gettext 0.22.5 hdfe23c8_3
    - gettext-tools 0.22.5 hdfe23c8_3
    - icu 75.1 h120a0e1_0
    - ld64_osx-64 711 h93b84b6_3
    - ld64_osx-arm64 711 hf597abb_3
    - libasprintf 0.22.5 hdfe23c8_3
    - libasprintf-devel 0.22.5 hdfe23c8_3
    - libclang-cpp18.1 18.1.8 default_h0c94c6a_3
    - libcxx 18.1.8 hd876a4e_6
    - libcxx-devel 18.1.8 h7c275be_6
    - libexpat 2.6.2 h73e2aa4_0
    - libffi 3.4.2 h0d85af4_5
    - libgettextpo 0.22.5 hdfe23c8_3
    - libgettextpo-devel 0.22.5 hdfe23c8_3
    - libiconv 1.17 hd75f5a5_2
    - libintl 0.22.5 hdfe23c8_3
    - libintl-devel 0.22.5 hdfe23c8_3
    - libllvm18 18.1.8 h9ce406d_2
    - libsqlite 3.46.0 h1b8f9f3_0
    - libxml2 2.12.7 heaf3512_4
    - libzlib 1.3.1 h87427d6_1
    - llvm-tools 18.1.8 h9ce406d_2
    - llvm-tools-18 18.1.8 h9ce406d_2
    - lz4-c 1.9.4 hf0c8a7f_0
    - ncurses 6.5 hf036a51_1
    - openssl 3.3.1 hd23fc13_3
    - popt 1.16 h7b079dc_2002
    - python 3.12.5 h37a9e06_0_cpython
    - readline 8.2 h9e318b2_1
    - rsync 3.3.0 h5aaac6a_0
    - sed 4.7 h3efe00b_1000
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - tk 8.6.13 h1abcd95_1
    - tzdata 2024a h8827d51_1
    - xxhash 0.8.2 h4140336_0
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.6 h915ae27_0
  host:
    - bzip2 1.0.8 h99b78c6_7
    - ca-certificates 2024.8.30 hf0a4a13_0
    - libexpat 2.6.2 hebf3989_0
    - libffi 3.4.2 h3422bc3_5
    - libsqlite 3.46.0 hfb93653_0
    - libzlib 1.3.1 hfb2fe0b_1
    - ncurses 6.5 h7bae524_1
    - openssl 3.3.1 h8359307_3
    - pip 24.2 pyh8b19718_1
    - python 3.12.5 h30c5eda_0_cpython
    - readline 8.2 h92ec313_1
    - setuptools 72.2.0 pyhd8ed1ab_0
    - tk 8.6.13 h5083fa2_1
    - tzdata 2024a h8827d51_1
    - wheel 0.44.0 pyhd8ed1ab_0
    - xz 5.2.6 h57fd34a_0
  run:
    - python >=3.12,<3.13.0a0
    - python >=3.12,<3.13.0a0 *_cpython
    - python_abi 3.12.* *_cp312
test:
  commands:
    - pip check
  imports:
    - jsonpointer
  requires:
    - pip
about:
  home: https://github.com/stefankoegl/python-json-pointer
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Identify specific nodes in a JSON document (RFC 6901)
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240902.2.1
  recipe-maintainers:
    - anguslees
    - xhochy
  remote_url: https://github.com/conda-forge/jsonpointer-feedstock
  sha: 0d5363373cb4f43a5f791d2896548cf1ccdf467e
