# This file created by conda-build 24.9.0
# ------------------------------------------------

package:
  name: libexpat
  version: 2.6.4
source:
  sha256: 8dc480b796163d4436e6f1352e71800a774f73dbae213f1860b60607d2a83ada
  url: https://github.com/libexpat/libexpat/releases/download/R_2_6_4/expat-2.6.4.tar.bz2
build:
  ignore_run_exports_from:
    - clangxx_osx-arm64 18.*
  number: 0
  string: h286801f_0
requirements:
  build:
    - ca-certificates 2024.8.30 h8857fd0_0
    - cctools_osx-64 1010.6 h525afad_1
    - cctools_osx-arm64 1010.6 h2dbf7ca_1
    - clang 18.1.8 default_h179603d_5
    - clang-18 18.1.8 default_h0c94c6a_5
    - clang_impl_osx-arm64 18.1.8 hadf8e89_21
    - clang_osx-arm64 18.1.8 h40be2b1_21
    - clangxx 18.1.8 default_h179603d_5
    - clangxx_impl_osx-arm64 18.1.8 hd2305f4_21
    - clangxx_osx-arm64 18.1.8 h40be2b1_21
    - compiler-rt 18.1.8 h1020d70_1
    - compiler-rt_osx-64 18.1.8 hf2b8a54_1
    - gnuconfig 2020.11.07 hd8ed1ab_0
    - icu 75.1 h120a0e1_0
    - ld64_osx-64 951.9 h4c85b5e_1
    - ld64_osx-arm64 951.9 hde547c4_1
    - libclang-cpp18.1 18.1.8 default_h0c94c6a_5
    - libcxx 19.1.3 hf95d169_0
    - libcxx-devel 18.1.8 h7c275be_7
    - libiconv 1.17 hd75f5a5_2
    - libllvm18 18.1.8 h9ce406d_2
    - libxml2 2.13.4 h12808cf_2
    - libzlib 1.3.1 hd23fc13_2
    - llvm-tools 18.1.8 h9ce406d_2
    - llvm-tools-18 18.1.8 h9ce406d_2
    - macosx_deployment_target_osx-arm64 11.0 h6553868_1
    - make 4.4.1 h00291cd_2
    - ncurses 6.5 hf036a51_1
    - openssl 3.3.2 hd23fc13_0
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1300.6.5 h390ca13_0
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.6 h915ae27_0
  host:
    - __osx >=11.0
  run:
    - __osx >=11.0
  run_constrained:
    - expat 2.6.4.*
test: {}
about:
  home: http://expat.sourceforge.net/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: Expat XML parser library in C
extra:
  copy_test_source_files: true
  feedstock-name: expat
  final: true
  flow_run_id: azure_20241107.2.1
  recipe-maintainers:
    - isuruf
    - kwilcox
    - mingwandroid
    - msarahan
    - ocefpaf
    - pelson
    - scopatz
  remote_url: https://github.com/conda-forge/expat-feedstock
  sha: 35492554e4b34921d9124289d61fa4de7db42321
