# This file created by conda-build 24.9.0
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Sun Oct 13 17:40:52 2024
# ------------------------------------------------

package:
  name: frozendict
  version: 2.4.6
source:
  fn: frozendict-2.4.6.tar.gz
  sha256: df7cd16470fbd26fc4969a208efadc46319334eb97def1ddf48919b351192b8e
  url: https://pypi.io/packages/source/f/frozendict/frozendict-2.4.6.tar.gz
build:
  number: '0'
  script: python -m pip install . --no-deps -vv
  string: py312h0bf5046_0
requirements:
  build:
    - bzip2 1.0.8 hfdf4475_7
    - ca-certificates 2024.8.30 h8857fd0_0
    - cctools_osx-64 1010.6 h98e843e_1
    - cctools_osx-arm64 1010.6 h7a13591_1
    - clang 17.0.6 default_he371ed4_7
    - clang-17 17.0.6 default_hb173f14_7
    - clang_impl_osx-arm64 17.0.6 h840ab8d_21
    - clang_osx-arm64 17.0.6 h40be2b1_21
    - clangxx 17.0.6 default_he371ed4_7
    - clangxx_impl_osx-arm64 17.0.6 ha3b5c75_21
    - compiler-rt 17.0.6 h1020d70_2
    - compiler-rt_osx-64 17.0.6 hf2b8a54_2
    - cross-python_osx-arm64 3.12 50_cpython
    - crossenv 1.5.0 pyhd8ed1ab_1
    - gettext 0.22.5 hdfe23c8_3
    - gettext-tools 0.22.5 hdfe23c8_3
    - icu 75.1 h120a0e1_0
    - ld64_osx-64 951.9 h38c89e5_1
    - ld64_osx-arm64 951.9 h2b3077e_1
    - libasprintf 0.22.5 hdfe23c8_3
    - libasprintf-devel 0.22.5 hdfe23c8_3
    - libclang-cpp17 17.0.6 default_hb173f14_7
    - libcxx 19.1.1 hf95d169_0
    - libcxx-devel 17.0.6 h8f8a49f_6
    - libexpat 2.6.3 hac325c4_0
    - libffi 3.4.2 h0d85af4_5
    - libgettextpo 0.22.5 hdfe23c8_3
    - libgettextpo-devel 0.22.5 hdfe23c8_3
    - libiconv 1.17 hd75f5a5_2
    - libintl 0.22.5 hdfe23c8_3
    - libintl-devel 0.22.5 hdfe23c8_3
    - libllvm17 17.0.6 hbedff68_1
    - libsqlite 3.46.1 h4b8f8c9_0
    - libxml2 2.12.7 heaf3512_4
    - libzlib 1.3.1 hd23fc13_2
    - llvm-tools 17.0.6 hbedff68_1
    - lz4-c 1.9.4 hf0c8a7f_0
    - macosx_deployment_target_osx-arm64 11.0 h6553868_1
    - ncurses 6.5 hf036a51_1
    - openssl 3.3.2 hd23fc13_0
    - popt 1.16 h7b079dc_2002
    - python 3.12.7 h8f8b54e_0_cpython
    - readline 8.2 h9e318b2_1
    - rsync 3.3.0 h5aaac6a_0
    - sed 4.7 h3efe00b_1000
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1300.6.5 h390ca13_0
    - tk 8.6.13 h1abcd95_1
    - tzdata 2024b hc8b5060_0
    - xxhash 0.8.2 h4140336_0
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.6 h915ae27_0
  host:
    - bzip2 1.0.8 h99b78c6_7
    - ca-certificates 2024.8.30 hf0a4a13_0
    - libexpat 2.6.3 hf9b8971_0
    - libffi 3.4.2 h3422bc3_5
    - libsqlite 3.46.1 hc14010f_0
    - libzlib 1.3.1 h8359307_2
    - ncurses 6.5 h7bae524_1
    - openssl 3.3.2 h8359307_0
    - pip 24.2 pyh8b19718_1
    - python 3.12.7 h739c21a_0_cpython
    - readline 8.2 h92ec313_1
    - setuptools 75.1.0 pyhd8ed1ab_0
    - tk 8.6.13 h5083fa2_1
    - tzdata 2024b hc8b5060_0
    - wheel 0.44.0 pyhd8ed1ab_0
    - xz 5.2.6 h57fd34a_0
  run:
    - __osx >=11.0
    - python >=3.12,<3.13.0a0
    - python >=3.12,<3.13.0a0 *_cpython
    - python_abi 3.12.* *_cp312
test:
  imports:
    - frozendict
about:
  dev_url: https://github.com/Marco-Sulla/python-frozendict
  home: https://github.com/Marco-Sulla/python-frozendict
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE.txt
  summary: An immutable dictionary
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20241013.2.1
  recipe-maintainers:
    - Marco-Sulla
    - ltalirz
  remote_url: https://github.com/conda-forge/frozendict-feedstock
  sha: 1ed7e1c6ccf60b2cf38cabaac62f06be804da503
