# This file created by conda-build 24.9.0
# ------------------------------------------------

package:
  name: libssh2
  version: 1.11.1
source:
  sha256: d9ec76cbe34db98eec3539fe2c899d26b0c837cb3eb466a56b0f109cabf658f7
  url: https://www.libssh2.org/download/libssh2-1.11.1.tar.gz
build:
  number: 0
  run_exports:
    - libssh2 >=1.11.1,<2.0a0
  string: h9cc3647_0
requirements:
  build:
    - ca-certificates 2024.8.30 h8857fd0_0
    - cctools_osx-arm64 1010.6 h59cac8b_1
    - clang_bootstrap_osx-arm64 11.1.0 h169cfcd_7
    - cmake-no-system 3.31.1 hbcac03e_0
    - icu 75.1 h120a0e1_0
    - ld64_osx-arm64 951.9 h1f06782_1
    - libcxx 19.1.4 hf95d169_0
    - libiconv 1.17 hd75f5a5_2
    - libllvm19 19.1.4 hc29ff6c_0
    - libxml2 2.13.5 h495214b_0
    - libzlib 1.3.1 hd23fc13_2
    - llvm-tools 19.1.4 h3fe3016_0
    - llvm-tools-19 19.1.4 he90a8e3_0
    - make 4.4.1 h00291cd_2
    - ncurses 6.5 hf036a51_1
    - openssl 3.4.0 hd471939_0
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1300.6.5 h390ca13_0
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.6 h915ae27_0
  host:
    - ca-certificates 2024.8.30 hf0a4a13_0
    - libzlib 1.3.1 h8359307_2
    - openssl 3.4.0 h39f12f2_0
    - zlib 1.3.1 h8359307_2
  run:
    - libzlib >=1.3.1,<2.0a0
    - openssl >=3.4.0,<4.0a0
test:
  commands:
    - test -f $PREFIX/include/libssh2.h
    - test -f $PREFIX/include/libssh2_publickey.h
    - test -f $PREFIX/include/libssh2_sftp.h
    - test ! -f $PREFIX/lib/libssh2.a
    - test -f $PREFIX/lib/libssh2${SHLIB_EXT}
about:
  description: 'libssh2 is a library implementing the SSH2 protocol, available under
    the revised BSD license.

    '
  dev_url: https://github.com/libssh2/libssh2
  home: https://www.libssh2.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: the SSH library
extra:
  copy_test_source_files: true
  feedstock-name: libssh2
  final: true
  flow_run_id: azure_20241123.2.1
  recipe-maintainers:
    - nehaljwani
    - ocefpaf
    - shadowwalkersb
    - xhochy
  remote_url: https://github.com/conda-forge/libssh2-feedstock
  sha: 66da9630a14e802670c8434ad6ffba388386603d
