# This file created by conda-build 25.1.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Feb  3 10:27:26 2025
# ------------------------------------------------

package:
  name: h2
  version: 4.2.0
source:
  fn: h2-4.2.0.tar.gz
  sha256: c8a52129695e88b1a0578d8d2cc6842bbd79128ac685463b887ee278126ad01f
  url: https://pypi.org/packages/source/h/h2/h2-4.2.0.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/h2_1738578511449/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/python
    -m pip install . --no-deps -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h4bc722e_7
    - ca-certificates 2025.1.31 hbcca054_0
    - ld_impl_linux-64 2.43 h712a8e2_2
    - libffi 3.4.2 h7f98852_5
    - libgcc 14.2.0 h77fa898_1
    - libgcc-ng 14.2.0 h69a702a_1
    - libgomp 14.2.0 h77fa898_1
    - liblzma 5.6.4 hb9d3cd8_0
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.48.0 hee588c1_1
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 hb9d3cd8_2
    - ncurses 6.5 h2d0b736_3
    - openssl 3.4.0 h7b32b05_1
    - pip 25.0 pyh8b19718_0
    - python 3.9.21 h9c0c6dc_1_cpython
    - readline 8.2 h8228510_1
    - setuptools 75.8.0 pyhff2d567_0
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2025a h78e105d_0
    - wheel 0.45.1 pyhd8ed1ab_1
  run:
    - hpack >=4.1,<5
    - hyperframe >=6.1,<7
    - python >=3.9
test:
  imports:
    - h2
  requires:
    - python 3.9.*
about:
  dev_url: https://github.com/python-hyper/hyper-h2
  home: http://python-hyper.org/h2/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: HTTP/2 State-Machine based protocol implementation
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20250203.2.1
  recipe-maintainers:
    - primozgodec
    - wiphoo
  remote_url: https://github.com/conda-forge/h2-feedstock
  sha: 253f46d8941eee96409821972fc23f6d93a339e7
