# This file created by conda-build 24.9.0
# ------------------------------------------------

package:
  name: reproc
  version: 14.2.5.post0
source:
  - patches:
      - 103-remove-fd-limit.patch
      - apple_gettime.patch
    sha256: 69467be0cfc80734b821c54ada263c8f1439f964314063f76b7cf256c3dc7ee8
    url: https://github.com/DaanDeMeyer/reproc/archive/v14.2.5.tar.gz
build:
  number: 0
  run_exports:
    - reproc >=14.2,<15.0a0
  string: h5505292_0
requirements:
  build:
    - bzip2 1.0.8 hfdf4475_7
    - c-ares 1.34.3 hf13058a_0
    - ca-certificates 2024.8.30 h8857fd0_0
    - cctools_osx-64 1010.6 h525afad_1
    - cctools_osx-arm64 1010.6 h2dbf7ca_1
    - clang 18.1.8 default_h179603d_5
    - clang-18 18.1.8 default_h0c94c6a_5
    - clang_impl_osx-arm64 18.1.8 hadf8e89_22
    - clang_osx-arm64 18.1.8 h1728699_22
    - clangxx 18.1.8 default_h179603d_5
    - cmake 3.30.5 h7243fc2_0
    - compiler-rt 18.1.8 h1020d70_1
    - compiler-rt_osx-64 18.1.8 hf2b8a54_1
    - icu 75.1 h120a0e1_0
    - krb5 1.21.3 h37d8d59_0
    - ld64_osx-64 951.9 h4c85b5e_1
    - ld64_osx-arm64 951.9 hde547c4_1
    - libclang-cpp18.1 18.1.8 default_h0c94c6a_5
    - libcurl 8.10.1 h58e7537_0
    - libcxx 19.1.3 hf95d169_0
    - libcxx-devel 18.1.8 h7c275be_7
    - libedit 3.1.20191231 h0678c8f_2
    - libev 4.33 h10d778d_2
    - libexpat 2.6.4 h240833e_0
    - libiconv 1.17 hd75f5a5_2
    - libllvm18 18.1.8 h9ce406d_2
    - libnghttp2 1.64.0 hc7306c3_0
    - libssh2 1.11.0 hd019ec5_0
    - libuv 1.49.2 hd79239c_0
    - libxml2 2.13.5 h495214b_0
    - libzlib 1.3.1 hd23fc13_2
    - llvm-tools 18.1.8 h9ce406d_2
    - llvm-tools-18 18.1.8 h9ce406d_2
    - macosx_deployment_target_osx-arm64 11.0 h6553868_1
    - ncurses 6.5 hf036a51_1
    - ninja 1.12.1 h3c5361c_0
    - openssl 3.4.0 hd471939_0
    - rhash 1.4.5 ha44c9a9_0
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1300.6.5 h390ca13_0
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.6 h915ae27_0
  host:
    - __osx >=11.0
  run:
    - __osx >=11.0
test:
  commands:
    - test -f ${PREFIX}/include/reproc/run.h
    - test -f ${PREFIX}/lib/libreproc${SHLIB_EXT}
    - test -f ${PREFIX}/lib/cmake/reproc/reproc-config.cmake
    - test ! -f ${PREFIX}/include/reproc++/run.hpp
    - test ! -f ${PREFIX}/lib/libreproc++${SHLIB_EXT}
    - test ! -f ${PREFIX}/lib/libreproc.a
    - test ! -f ${PREFIX}/lib/libreproc++.a
    - test ! -f ${PREFIX}/lib/cmake/reproc++/reproc++-config.cmake
    - cmake -G Ninja -S test-c/ -B build-test-c/ ${CMAKE_ARGS}
    - cmake --build build-test-c/
    - cmake --build build-test-c/ --target test
  files:
    - test-c/
  requires:
    - clang_osx-arm64 18.*
    - cmake
    - ninja
about:
  dev_url: https://github.com/DaanDeMeyer/reproc
  home: https://github.com/DaanDeMeyer/reproc
  license: MIT
  license_file: LICENSE
  summary: reproc (Redirected Process) is a cross-platform C/C++ library that simplifies
    starting, stopping and communicating with external programs.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20241118.2.1
  recipe-maintainers:
    - AntoinePrv
    - DaanDeMeyer
    - wolfv
  remote_url: https://github.com/conda-forge/reproc-feedstock
  sha: 0d8c38aefb9f2dc6ba1129b03d070f7f082dafff
