# This file created by conda-build 24.5.1
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Thu Jun 27 04:34:43 2024
# ------------------------------------------------

package:
  name: krb5
  version: 1.21.3
source:
  sha256: 2157d92020d408ed63ebcd886a92d1346a1383b0f91123a0473b4f69b4a24861
  url: https://github.com/krb5/krb5/archive/krb5-1.21.3-final.tar.gz
build:
  missing_dso_whitelist:
    - /usr/lib/libresolv.9.dylib
  number: '0'
  run_exports:
    - krb5 >=1.21.3,<1.22.0a0
  string: h237132a_0
requirements:
  build:
    - autoconf 2.71 pl5321hed12c24_1
    - bison 3.8.2 hd7636e7_0
    - bzip2 1.0.8 h10d778d_5
    - ca-certificates 2024.6.2 h8857fd0_0
    - cctools_osx-64 986 ha1c5b94_0
    - cctools_osx-arm64 986 h7bb7a8e_0
    - clang 16.0.6 default_ha3b9224_8
    - clang-16 16.0.6 default_h4c8afb6_8
    - clang_impl_osx-arm64 16.0.6 ha81d56d_16
    - clang_osx-arm64 16.0.6 h40be2b1_16
    - clangxx 16.0.6 default_ha3b9224_8
    - clangxx_impl_osx-arm64 16.0.6 h4a79b72_16
    - clangxx_osx-arm64 16.0.6 h40be2b1_16
    - compiler-rt 16.0.6 ha38d28d_2
    - compiler-rt_osx-64 16.0.6 ha38d28d_2
    - flex 2.6.4 hcc69e7b_1004
    - gettext 0.22.5 h5ff76d1_2
    - gettext-tools 0.22.5 h5ff76d1_2
    - icu 73.2 hf5e326d_0
    - ld64_osx-64 711 ha20a434_0
    - ld64_osx-arm64 711 h6aa3cc8_0
    - libasprintf 0.22.5 h5ff76d1_2
    - libasprintf-devel 0.22.5 h5ff76d1_2
    - libclang-cpp16 16.0.6 default_h4c8afb6_8
    - libcxx 17.0.6 h8d2f0da_1
    - libexpat 2.6.2 h73e2aa4_0
    - libffi 3.4.2 h0d85af4_5
    - libgettextpo 0.22.5 h5ff76d1_2
    - libgettextpo-devel 0.22.5 h5ff76d1_2
    - libiconv 1.17 hd75f5a5_2
    - libintl 0.22.5 h5ff76d1_2
    - libintl-devel 0.22.5 h5ff76d1_2
    - libllvm16 16.0.6 hbedff68_3
    - libsqlite 3.46.0 h1b8f9f3_0
    - libtool 2.4.7 hf0c8a7f_0
    - libxml2 2.12.7 h3e169fe_1
    - libzlib 1.3.1 h87427d6_1
    - llvm-tools 16.0.6 hbedff68_3
    - m4 1.4.18 haf1e3a3_1001
    - macosx_deployment_target_osx-arm64 11.0 h6553868_1
    - make 4.3 h22f3db7_1
    - ncurses 6.5 h5846eda_0
    - openssl 3.3.1 h87427d6_1
    - perl 5.32.1 7_h10d778d_perl5
    - pkg-config 0.29.2 ha3d46e9_1008
    - python 3.12.4 h37a9e06_0_cpython
    - readline 8.2 h9e318b2_1
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - tk 8.6.13 h1abcd95_1
    - tzdata 2024a h0c530f3_0
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.6 h915ae27_0
  host:
    - ca-certificates 2024.6.2 hf0a4a13_0
    - libcxx 17.0.6 he7857fb_1
    - libedit 3.1.20191231 hc8eb9b7_2
    - ncurses 6.5 hb89a1cb_0
    - openssl 3.3.1 hfb2fe0b_1
  run:
    - __osx >=11.0
    - libcxx >=16
    - libedit >=3.1.20191231,<3.2.0a0
    - libedit >=3.1.20191231,<4.0a0
    - openssl >=3.3.1,<4.0a0
test:
  commands:
    - test -f ${PREFIX}/lib/libkrb5${SHLIB_EXT}
about:
  home: http://web.mit.edu/kerberos/
  license: MIT
  license_file: doc/notice.rst
  summary: A network authentication protocol.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240627.1.1
  recipe-maintainers:
    - mariusvniekerk
    - mingwandroid
    - ocefpaf
    - pelson
    - wolfv
  remote_url: https://github.com/conda-forge/krb5-feedstock
  sha: 23ac81ca671fccb138f6ae25cfab72c15b29f6b0
