# This file created by conda-build 24.11.2
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Tue Jan  7 11:05:50 2025
# ------------------------------------------------

package:
  name: ruamel.yaml
  version: 0.18.10
source:
  sha256: 20c86ab29ac2153f80a428e1254a8adf686d3383df04490514ca3b79a362db58
  url: https://pypi.org/packages/source/r/ruamel.yaml/ruamel.yaml-0.18.10.tar.gz
build:
  number: '0'
  script: /Users/runner/miniforge3/conda-bld/ruamel.yaml_1736248058782/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/python
    -m pip install . --no-deps -vv
  script_env:
    - RUAMEL_NO_LONG_DESCRIPTION=1
  string: py312hea69d52_0
requirements:
  build:
    - bzip2 1.0.8 hfdf4475_7
    - ca-certificates 2024.12.14 h8857fd0_0
    - cctools_osx-64 1010.6 h00edd4c_2
    - cctools_osx-arm64 1010.6 h71f0a72_2
    - clang 18.1.8 default_h179603d_5
    - clang-18 18.1.8 default_h0c94c6a_5
    - clang_impl_osx-arm64 18.1.8 hadf8e89_23
    - clang_osx-arm64 18.1.8 h1728699_23
    - clangxx 18.1.8 default_h179603d_5
    - clangxx_impl_osx-arm64 18.1.8 hd2305f4_23
    - compiler-rt 18.1.8 h1020d70_1
    - compiler-rt_osx-64 18.1.8 hf2b8a54_1
    - cross-python_osx-arm64 3.12 50_cpython
    - crossenv 1.5.0 pyhd8ed1ab_1
    - gettext 0.22.5 hdfe23c8_3
    - gettext-tools 0.22.5 hdfe23c8_3
    - ld64_osx-64 951.9 hc8d1a19_2
    - ld64_osx-arm64 951.9 h148c8d5_2
    - libasprintf 0.22.5 hdfe23c8_3
    - libasprintf-devel 0.22.5 hdfe23c8_3
    - libclang-cpp18.1 18.1.8 default_h0c94c6a_5
    - libcxx 19.1.6 hf95d169_1
    - libcxx-devel 18.1.8 h7c275be_7
    - libexpat 2.6.4 h240833e_0
    - libffi 3.4.2 h0d85af4_5
    - libgettextpo 0.22.5 hdfe23c8_3
    - libgettextpo-devel 0.22.5 hdfe23c8_3
    - libiconv 1.17 hd75f5a5_2
    - libintl 0.22.5 hdfe23c8_3
    - libintl-devel 0.22.5 hdfe23c8_3
    - libllvm18 18.1.8 h9ce406d_2
    - liblzma 5.6.3 hd471939_1
    - libsqlite 3.47.2 hdb6dae5_0
    - libxml2 2.13.5 he8ee3e7_1
    - libzlib 1.3.1 hd23fc13_2
    - llvm-tools 18.1.8 h9ce406d_2
    - llvm-tools-18 18.1.8 h9ce406d_2
    - lz4-c 1.10.0 h240833e_1
    - macosx_deployment_target_osx-arm64 11.0 h6553868_2
    - ncurses 6.5 hf036a51_1
    - openssl 3.4.0 hc426f3f_1
    - popt 1.16 h7b079dc_2002
    - python 3.12.8 h9ccd52b_1_cpython
    - readline 8.2 h9e318b2_1
    - rsync 3.3.0 hbf82b91_1
    - sed 4.7 h3efe00b_1000
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1300.6.5 h390ca13_0
    - tk 8.6.13 h1abcd95_1
    - tzdata 2024b hc8b5060_0
    - xxhash 0.8.2 h4140336_0
    - zstd 1.5.6 h915ae27_0
  host:
    - bzip2 1.0.8 h99b78c6_7
    - ca-certificates 2024.12.14 hf0a4a13_0
    - libexpat 2.6.4 h286801f_0
    - libffi 3.4.2 h3422bc3_5
    - liblzma 5.6.3 h39f12f2_1
    - libsqlite 3.47.2 h3f77e49_0
    - libzlib 1.3.1 h8359307_2
    - ncurses 6.5 h7bae524_1
    - openssl 3.4.0 h81ee809_1
    - pip 24.3.1 pyh8b19718_2
    - python 3.12.8 hc22306f_1_cpython
    - python_abi 3.12 5_cp312
    - readline 8.2 h92ec313_1
    - ruamel 1.0 py312h81bd7bf_9
    - setuptools 75.6.0 pyhff2d567_1
    - tk 8.6.13 h5083fa2_1
    - tzdata 2024b hc8b5060_0
    - wheel 0.45.1 pyhd8ed1ab_1
  run:
    - __osx >=11.0
    - python >=3.12,<3.13.0a0
    - python >=3.12,<3.13.0a0 *_cpython
    - python_abi 3.12.* *_cp312
    - ruamel.yaml.clib >=0.1.2
test:
  imports:
    - ruamel.yaml
about:
  home: https://sourceforge.net/p/ruamel-yaml
  license: MIT
  license_file: LICENSE
  summary: A YAML package for Python. It is a derivative of Kirill Simonov's PyYAML
    3.11 which supports YAML1.1
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20250107.1.1
  recipe-maintainers:
    - davidbrochart
    - jakirkham
    - mbargull
    - mwcraig
    - ocefpaf
    - pelson
    - xhochy
  remote_url: https://github.com/conda-forge/ruamel.yaml-feedstock
  sha: cb2ce38646fcb9460de7c09ae562f6b65c015f79
