# This file created by conda-build 24.11.2
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Thu Jan  9 22:02:26 2025
# ------------------------------------------------

package:
  name: conda
  version: 24.11.3
source:
  fn: conda-24.11.3.tar.gz
  sha256: 5c4e352e737315b6dc86448abbb0c76834b21ef1663b02c797d4f55af8be981c
  url: https://github.com/conda/conda/releases/download/24.11.3/conda-24.11.3.tar.gz
build:
  always_include_files:
    - bin/activate
    - bin/conda
    - bin/deactivate
  number: '0'
  script: /Users/runner/miniforge3/conda-bld/conda_1736460303265/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
    -m pip install . --no-deps --no-build-isolation -vv && /Users/runner/miniforge3/conda-bld/conda_1736460303265/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
    -m conda init --install
  string: py312h81bd7bf_0
requirements:
  build:
    - bzip2 1.0.8 hfdf4475_7
    - ca-certificates 2024.12.14 h8857fd0_0
    - cctools_osx-64 1010.6 hadbd6bd_2
    - cctools_osx-arm64 1010.6 h563b5bc_2
    - clang 19.1.6 default_h576c50e_0
    - clang-19 19.1.6 default_h3571c67_0
    - clang_impl_osx-arm64 19.1.6 h252a79b_23
    - clang_osx-arm64 19.1.6 h1728699_23
    - clangxx 19.1.6 default_heb2e8d1_0
    - clangxx_impl_osx-arm64 19.1.6 hb1f5f5c_23
    - compiler-rt 19.1.6 h52031e2_0
    - compiler-rt_osx-64 19.1.6 hc6f8467_0
    - cross-python_osx-arm64 3.12 50_cpython
    - crossenv 1.5.0 pyhd8ed1ab_1
    - gettext 0.22.5 hdfe23c8_3
    - gettext-tools 0.22.5 hdfe23c8_3
    - ld64_osx-64 951.9 h9d2de3d_2
    - ld64_osx-arm64 951.9 hdfa8970_2
    - libasprintf 0.22.5 hdfe23c8_3
    - libasprintf-devel 0.22.5 hdfe23c8_3
    - libclang-cpp19.1 19.1.6 default_h3571c67_0
    - libcxx 19.1.6 hf95d169_1
    - libcxx-devel 19.1.6 h7c275be_1
    - libexpat 2.6.4 h240833e_0
    - libffi 3.4.2 h0d85af4_5
    - libgettextpo 0.22.5 hdfe23c8_3
    - libgettextpo-devel 0.22.5 hdfe23c8_3
    - libiconv 1.17 hd75f5a5_2
    - libintl 0.22.5 hdfe23c8_3
    - libintl-devel 0.22.5 hdfe23c8_3
    - libllvm19 19.1.6 hc29ff6c_0
    - liblzma 5.6.3 hd471939_1
    - libsqlite 3.47.2 hdb6dae5_0
    - libxml2 2.13.5 he8ee3e7_1
    - libzlib 1.3.1 hd23fc13_2
    - llvm-tools 19.1.6 h3fe3016_0
    - llvm-tools-19 19.1.6 he90a8e3_0
    - lz4-c 1.10.0 h240833e_1
    - ncurses 6.5 hf036a51_1
    - openssl 3.4.0 hc426f3f_1
    - popt 1.16 h7b079dc_2002
    - python 3.12.8 h9ccd52b_1_cpython
    - readline 8.2 h9e318b2_1
    - rsync 3.3.0 hbf82b91_1
    - sed 4.7 h3efe00b_1000
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1300.6.5 h390ca13_0
    - tk 8.6.13 h1abcd95_1
    - tzdata 2024b hc8b5060_0
    - xxhash 0.8.2 h4140336_0
    - zstd 1.5.6 h915ae27_0
  host:
    - boltons 24.0.0 pyhd8ed1ab_1
    - brotli-python 1.1.0 py312hde4cb15_2
    - bzip2 1.0.8 h99b78c6_7
    - ca-certificates 2024.12.14 hf0a4a13_0
    - certifi 2024.12.14 pyhd8ed1ab_0
    - cffi 1.17.1 py312h0fad829_0
    - charset-normalizer 3.4.1 pyhd8ed1ab_0
    - colorama 0.4.6 pyhd8ed1ab_1
    - editables 0.5 pyhd8ed1ab_1
    - h2 4.1.0 pyhd8ed1ab_1
    - hatch-vcs 0.4.0 pyhd8ed1ab_1
    - hatchling 1.27.0 pypyhd8ed1ab_0
    - hpack 4.0.0 pyhd8ed1ab_1
    - hyperframe 6.0.1 pyhd8ed1ab_1
    - idna 3.10 pyhd8ed1ab_1
    - importlib-metadata 8.5.0 pyha770c72_1
    - libcxx 19.1.6 ha82da77_1
    - libexpat 2.6.4 h286801f_0
    - libffi 3.4.2 h3422bc3_5
    - liblzma 5.6.3 h39f12f2_1
    - libsqlite 3.47.2 h3f77e49_0
    - libzlib 1.3.1 h8359307_2
    - menuinst 2.2.0 py312h81bd7bf_0
    - ncurses 6.5 h7bae524_1
    - openssl 3.4.0 h81ee809_1
    - packaging 24.2 pyhd8ed1ab_2
    - pathspec 0.12.1 pyhd8ed1ab_1
    - pip 24.3.1 pyh8b19718_2
    - platformdirs 4.3.6 pyhd8ed1ab_1
    - pluggy 1.5.0 pyhd8ed1ab_1
    - pycparser 2.22 pyh29332c3_1
    - pysocks 1.7.1 pyha55dd90_7
    - python 3.12.8 hc22306f_1_cpython
    - python_abi 3.12 5_cp312
    - readline 8.2 h92ec313_1
    - requests 2.32.3 pyhd8ed1ab_1
    - ruamel.yaml 0.18.10 py312hea69d52_0
    - ruamel.yaml.clib 0.2.8 py312h0bf5046_1
    - setuptools 75.7.0 pyhff2d567_0
    - setuptools-scm 8.1.0 pyhd8ed1ab_1
    - tk 8.6.13 h5083fa2_1
    - tomli 2.2.1 pyhd8ed1ab_1
    - tqdm 4.67.1 pyhd8ed1ab_1
    - trove-classifiers 2025.1.7.14 pyhd8ed1ab_0
    - typing-extensions 4.12.2 hd8ed1ab_1
    - typing_extensions 4.12.2 pyha770c72_1
    - tzdata 2024b hc8b5060_0
    - urllib3 2.3.0 pyhd8ed1ab_0
    - wheel 0.45.1 pyhd8ed1ab_1
    - zipp 3.21.0 pyhd8ed1ab_1
    - zstandard 0.23.0 py312h15fbf35_1
    - zstd 1.5.6 hb46c0d2_0
  run:
    - archspec >=0.2.3
    - boltons >=23.0.0
    - charset-normalizer
    - conda-libmamba-solver >=23.11.0
    - conda-package-handling >=2.2.0
    - distro >=1.5.0
    - frozendict >=2.4.2
    - jsonpatch >=1.32
    - menuinst >=2
    - packaging >=23.0
    - platformdirs >=3.10.0
    - pluggy >=1.0.0
    - pycosat >=0.6.3
    - python >=3.12,<3.13.0a0
    - python >=3.12,<3.13.0a0 *_cpython
    - python_abi 3.12.* *_cp312
    - requests >=2.28.0,<3
    - ruamel.yaml >=0.11.14,<0.19
    - setuptools >=60.0.0
    - tqdm >=4
    - truststore >=0.8.0
    - zstandard >=0.19.0
  run_constrained:
    - conda-build >=24.3
    - conda-content-trust >=0.1.1
    - conda-env >=2.6
test:
  downstreams: null
  files:
    - commands_to_test.sh
    - test_runner.sh
  imports:
    - conda
    - conda_env
  requires:
    - mock
    - pexpect
    - responses
about:
  description: 'Conda is an open source package management system and environment

    management system for installing multiple versions of software packages

    and their dependencies and switching easily between them. It works on

    Linux, OS X and Windows, and was created for Python programs but can

    package and distribute any software.

    '
  dev_url: https://github.com/conda/conda
  doc_url: https://docs.conda.io/projects/conda/en/stable/
  home: https://conda.io
  license: BSD-3-Clause
  license_file: LICENSE
  summary: OS-agnostic, system-level binary package and environment manager.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20250109.1.1
  recipe-maintainers:
    - beeankha
    - dbast
    - isuruf
    - jakirkham
    - jezdez
    - kenodegard
    - mbargull
    - ocefpaf
  remote_url: https://github.com/conda-forge/conda-feedstock
  sha: 2f6ae5e0afc9e2ed3e7bc99189ba3e7eb548e983
