# This file created by conda-build 25.1.2
# ------------------------------------------------

package:
  name: openssl
  version: 3.4.1
source:
  sha256: 002a2d6b30b58bf4bea46c43bdd96365aaf8daa6c428782aa4feee06da197df3
  url: https://github.com/openssl/openssl/releases/download/openssl-3.4.1/openssl-3.4.1.tar.gz
build:
  number: 0
  run_exports:
    - openssl >=3.4.1,<4.0a0
  string: h81ee809_0
requirements:
  build:
    - clang_bootstrap_osx-arm64 18.1.8 hf1725c4_23
    - macosx_deployment_target_osx-arm64 11.0 h6553868_2
    - make 4.4.1 h00291cd_2
    - perl 5.32.1 7_h10d778d_perl5
  host:
    - __osx >=11.0
  run:
    - __osx >=11.0
    - ca-certificates
test:
  commands:
    - touch checksum.txt
    - $PREFIX/bin/openssl sha256 checksum.txt
    - pkg-config --print-errors --exact-version "3.4.1" openssl
    - if [[ "$(pkg-config --variable=prefix openssl)" == "" ]]; then exit 1; fi
  requires:
    - pkg-config
    - ripgrep
about:
  dev_url: https://github.com/openssl/openssl
  doc_url: https://docs.openssl.org/master/
  home: https://www.openssl.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: OpenSSL is an open-source implementation of the SSL and TLS protocols
extra:
  copy_test_source_files: true
  feedstock-name: openssl
  final: true
  flow_run_id: azure_20250211.2.1
  recipe-maintainers:
    - h-vetinari
    - jakirkham
    - msarahan
    - ocefpaf
    - pelson
  remote_url: https://github.com/conda-forge/openssl-feedstock
  sha: 83b5e2a793bc95d19e6cc2d9d28068f1a6ff6b79
