# This file created by conda-build 24.9.0
# ------------------------------------------------

package:
  name: libnghttp2
  version: 1.64.0
source:
  sha256: 20e73f3cf9db3f05988996ac8b3a99ed529f4565ca91a49eb0550498e10621e8
  url: https://github.com/nghttp2/nghttp2/releases/download/v1.64.0/nghttp2-1.64.0.tar.gz
build:
  number: 0
  run_exports:
    - libnghttp2 >=1.64.0,<2.0a0
  string: h6d7220d_0
requirements:
  build:
    - ca-certificates 2024.8.30 h8857fd0_0
    - cctools_osx-64 1010.6 h98e843e_1
    - cctools_osx-arm64 1010.6 h7a13591_1
    - clang 17.0.6 default_he371ed4_7
    - clang-17 17.0.6 default_hb173f14_7
    - clang_impl_osx-arm64 17.0.6 h840ab8d_21
    - clang_osx-arm64 17.0.6 h40be2b1_21
    - clangxx 17.0.6 default_he371ed4_7
    - clangxx_impl_osx-arm64 17.0.6 ha3b5c75_21
    - clangxx_osx-arm64 17.0.6 h40be2b1_21
    - compiler-rt 17.0.6 h1020d70_2
    - compiler-rt_osx-64 17.0.6 hf2b8a54_2
    - icu 75.1 h120a0e1_0
    - ld64_osx-64 951.9 h38c89e5_1
    - ld64_osx-arm64 951.9 h2b3077e_1
    - libclang-cpp17 17.0.6 default_hb173f14_7
    - libcxx 19.1.2 hf95d169_0
    - libcxx-devel 17.0.6 h8f8a49f_6
    - libiconv 1.17 hd75f5a5_2
    - libllvm17 17.0.6 hbedff68_1
    - libxml2 2.12.7 heaf3512_4
    - libzlib 1.3.1 hd23fc13_2
    - llvm-tools 17.0.6 hbedff68_1
    - macosx_deployment_target_osx-arm64 11.0 h6553868_1
    - make 4.4.1 h00291cd_2
    - ncurses 6.5 hf036a51_1
    - openssl 3.3.2 hd23fc13_0
    - pkg-config 0.29.2 hf7e621a_1009
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1300.6.5 h390ca13_0
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.6 h915ae27_0
  host:
    - c-ares 1.34.2 h7ab814d_0
    - ca-certificates 2024.8.30 hf0a4a13_0
    - libcxx 19.1.2 ha82da77_0
    - libev 4.33 h93a5062_2
    - libzlib 1.3.1 h8359307_2
    - openssl 3.3.2 h8359307_0
    - zlib 1.3.1 h8359307_2
  run:
    - __osx >=11.0
    - c-ares >=1.34.2,<2.0a0
    - libcxx >=17
    - libev >=4.33,<4.34.0a0
    - libev >=4.33,<5.0a0
    - libzlib >=1.3.1,<2.0a0
    - openssl >=3.3.2,<4.0a0
test:
  commands:
    - nghttp -nv https://nghttp2.org
    - test ! -f ${PREFIX}/lib/libnghttp2.a
about:
  description: 'This is an implementation of the Hypertext Transfer Protocol version
    2 in C.


    The framing layer of HTTP/2 is implemented as a reusable C library. On top

    of that, we have implemented an HTTP/2 client, server and proxy. We have

    also developed load test and benchmarking tools for HTTP/2.

    '
  dev_url: https://github.com/nghttp2/nghttp2
  doc_url: https://nghttp2.org/documentation/
  home: http://github.com/nghttp2/nghttp2
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: This is an implementation of Hypertext Transfer Protocol version 2.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20241022.1.1
  recipe-maintainers:
    - cpaulik
    - mariusvniekerk
    - wolfv
  remote_url: https://github.com/conda-forge/nghttp2-feedstock
  sha: 970a96e770f3d092d485da395f750621d5c68510
