# This file created by conda-build 24.3.0
# ------------------------------------------------

package:
  name: zstd
  version: 1.5.6
source:
  patches:
    - 4019.patch
  sha256: 30f35f71c1203369dc979ecde0400ffea93c27391bfd2ac5a9715d2173d92ff7
  url: https://github.com/facebook/zstd/archive/v1.5.6.tar.gz
build:
  number: 0
  run_exports:
    - zstd >=1.5.6,<1.6.0a0
  string: hb46c0d2_0
requirements:
  build:
    - clang_bootstrap_osx-arm64 16.0.6 h223edda_12
    - cmake-no-system 3.29.2 h73e2aa4_0
    - libcxx 16.0.6 hd57cbcb_0
    - macosx_deployment_target_osx-arm64 11.0 h6553868_1
    - make 4.3 h22f3db7_1
    - ninja 1.12.0 h7728843_0
  host:
    - libzlib 1.2.13 h53f4e23_5
    - zlib 1.2.13 h53f4e23_5
  run:
    - __osx >=11.0
    - libzlib >=1.2.13,<1.3.0a0
test:
  commands:
    - test -f ${PREFIX}/lib/libzstd.dylib
    - test ! -f ${PREFIX}/lib/libzstd.a
    - test -f ${PREFIX}/include/zstd.h
    - zstd -be -i5
    - test -f ${PREFIX}/lib/pkgconfig/libzstd.pc
    - export PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig
    - pkg-config --cflags libzstd
    - cd cf_test
  files:
    - cf_test/
  requires:
    - clang_bootstrap_osx-arm64 16.*
    - cmake
    - pkg-config
about:
  description: 'Zstandard is a real-time compression algorithm, providing high compression

    ratios. It offers a very wide range of compression / speed trade-off, while

    being backed by a very fast decoder. It also offers a special mode for

    small data, called dictionary compression, and can create dictionaries from

    any sample set. Zstandard library is provided as open source software using

    a BSD license.

    '
  dev_url: https://github.com/facebook/zstd
  doc_url: https://facebook.github.io/zstd/zstd_manual.html
  home: http://www.zstd.net
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Zstandard - Fast real-time compression algorithm
extra:
  copy_test_source_files: true
  feedstock-name: zstd
  final: true
  flow_run_id: azure_20240503.2.1
  recipe-maintainers:
    - JohanMabille
    - hmaarrfk
    - msarahan
    - rmax
    - xhochy
  remote_url: https://github.com/conda-forge/zstd-feedstock
  sha: fe360b67052e184a180a3fb0dbf2dec8cd582be1
