# This file created by conda-build 24.3.0
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Fri Apr 19 08:32:55 2024
# ------------------------------------------------

package:
  name: lzo
  version: '2.10'
source:
  sha256: c0f892943208266f9b6543b3ae308fab6284c5c90e627931446fb49b4221a072
  url: http://www.oberhumer.com/opensource/lzo/download/lzo-2.10.tar.gz
build:
  number: '1001'
  run_exports:
    - lzo >=2.10,<3.0a0
  string: h93a5062_1001
requirements:
  build:
    - bzip2 1.0.8 h10d778d_5
    - c-ares 1.28.1 h10d778d_0
    - ca-certificates 2024.2.2 h8857fd0_0
    - cctools_osx-64 986 ha1c5b94_0
    - cctools_osx-arm64 986 h7bb7a8e_0
    - clang 16.0.6 hdae98eb_6
    - clang-16 16.0.6 default_h7151d67_6
    - clang_impl_osx-arm64 16.0.6 ha81d56d_11
    - clang_osx-arm64 16.0.6 h40be2b1_11
    - clangxx 16.0.6 default_h7151d67_6
    - cmake 3.29.2 h7c85d92_0
    - compiler-rt 16.0.6 ha38d28d_2
    - compiler-rt_osx-64 16.0.6 ha38d28d_2
    - icu 73.2 hf5e326d_0
    - krb5 1.21.2 hb884880_0
    - ld64_osx-64 711 ha20a434_0
    - ld64_osx-arm64 711 h6aa3cc8_0
    - libclang-cpp16 16.0.6 default_h7151d67_6
    - libcurl 8.7.1 h726d00d_0
    - libcxx 16.0.6 hd57cbcb_0
    - libedit 3.1.20191231 h0678c8f_2
    - libev 4.33 h10d778d_2
    - libexpat 2.6.2 h73e2aa4_0
    - libiconv 1.17 hd75f5a5_2
    - libllvm16 16.0.6 hbedff68_3
    - libnghttp2 1.58.0 h64cf6d3_1
    - libssh2 1.11.0 hd019ec5_0
    - libuv 1.48.0 h67532ce_0
    - libxml2 2.12.6 hc0ae0f7_2
    - libzlib 1.2.13 h8a1eda9_5
    - llvm-tools 16.0.6 hbedff68_3
    - make 4.3 h22f3db7_1
    - ncurses 6.4.20240210 h73e2aa4_0
    - openssl 3.2.1 hd75f5a5_1
    - rhash 1.4.4 h0dc2134_0
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.5 h829000d_0
  run: []
test:
  commands:
    - test -f ${PREFIX}/include/lzo/lzoconf.h
    - test -f ${PREFIX}/lib/liblzo2.a
    - test -f ${PREFIX}/lib/liblzo2${SHLIB_EXT}
about:
  description: 'LZO offers pretty fast compression and extremely fast decompression.

    MiniLZO is a very lightweight subset of the LZO library.

    '
  home: http://www.oberhumer.com/opensource/lzo/
  license: GPL-2.0-or-later
  license_family: GPL2
  license_file: COPYING
  summary: LZO is a portable lossless data compression library written in ANSI C.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240419.1.1
  recipe-maintainers:
    - ocefpaf
    - rmax
  remote_url: https://github.com/conda-forge/lzo-feedstock
  sha: d209d63d9c6a0269f2ee2b2def1a6c2e697e6607
