# This file created by conda-build 24.9.0
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Sat Nov  9 10:08:20 2024
# ------------------------------------------------

package:
  name: menuinst
  version: 2.2.0
source:
  sha256: c225bacefa9ee216e678d929d375e34f10856d87c1aba70a57c3d7974fda0cb7
  url: https://github.com/conda/menuinst/archive/2.2.0.tar.gz
build:
  number: '0'
  script:
    - /Users/runner/miniforge3/conda-bld/menuinst_1731147022576/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python
      -m pip install . -vv
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION=2.2.0
  string: py312h81bd7bf_0
requirements:
  build:
    - bzip2 1.0.8 hfdf4475_7
    - ca-certificates 2024.8.30 h8857fd0_0
    - cctools_osx-64 1010.6 hd0ff2cf_1
    - cctools_osx-arm64 1010.6 h59cac8b_1
    - clang 19.1.3 default_h4bb2e93_0
    - clang-19 19.1.3 default_hed3c1ff_0
    - clang_impl_osx-arm64 19.1.3 h00131ed_21
    - clang_osx-arm64 19.1.3 h40be2b1_21
    - clangxx 19.1.3 default_h4bb2e93_0
    - clangxx_impl_osx-arm64 19.1.3 ha510ad7_21
    - compiler-rt 19.1.3 hf2491d2_0
    - compiler-rt_osx-64 19.1.3 h9518668_0
    - cross-python_osx-arm64 3.12 50_cpython
    - crossenv 1.5.0 pyhd8ed1ab_1
    - gettext 0.22.5 hdfe23c8_3
    - gettext-tools 0.22.5 hdfe23c8_3
    - icu 75.1 h120a0e1_0
    - ld64_osx-64 951.9 h3c7722d_1
    - ld64_osx-arm64 951.9 h1f06782_1
    - libasprintf 0.22.5 hdfe23c8_3
    - libasprintf-devel 0.22.5 hdfe23c8_3
    - libclang-cpp19.1 19.1.3 default_hed3c1ff_0
    - libcxx 19.1.3 hf95d169_0
    - libcxx-devel 19.1.3 h7c275be_0
    - libexpat 2.6.4 h240833e_0
    - libffi 3.4.2 h0d85af4_5
    - libgettextpo 0.22.5 hdfe23c8_3
    - libgettextpo-devel 0.22.5 hdfe23c8_3
    - libiconv 1.17 hd75f5a5_2
    - libintl 0.22.5 hdfe23c8_3
    - libintl-devel 0.22.5 hdfe23c8_3
    - libllvm19 19.1.3 h1e63acb_0
    - libsqlite 3.47.0 h2f8c449_1
    - libxml2 2.13.4 h12808cf_2
    - libzlib 1.3.1 hd23fc13_2
    - llvm-tools 19.1.3 h062cec2_0
    - llvm-tools-19 19.1.3 h65ece69_0
    - lz4-c 1.9.4 hf0c8a7f_0
    - ncurses 6.5 hf036a51_1
    - openssl 3.3.2 hd23fc13_0
    - popt 1.16 h7b079dc_2002
    - python 3.12.7 h8f8b54e_0_cpython
    - readline 8.2 h9e318b2_1
    - rsync 3.3.0 h5aaac6a_0
    - sed 4.7 h3efe00b_1000
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1300.6.5 h390ca13_0
    - tk 8.6.13 h1abcd95_1
    - tzdata 2024b hc8b5060_0
    - xxhash 0.8.2 h4140336_0
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.6 h915ae27_0
  host:
    - bzip2 1.0.8 h99b78c6_7
    - ca-certificates 2024.8.30 hf0a4a13_0
    - libexpat 2.6.4 h286801f_0
    - libffi 3.4.2 h3422bc3_5
    - libsqlite 3.47.0 hbaaea75_1
    - libzlib 1.3.1 h8359307_2
    - ncurses 6.5 h7bae524_1
    - openssl 3.3.2 h8359307_0
    - packaging 24.1 pyhd8ed1ab_0
    - pip 24.3.1 pyh8b19718_0
    - python 3.12.7 h739c21a_0_cpython
    - readline 8.2 h92ec313_1
    - setuptools 75.3.0 pyhd8ed1ab_0
    - setuptools-scm 8.1.0 pyhd8ed1ab_0
    - setuptools_scm 8.1.0 hd8ed1ab_0
    - tk 8.6.13 h5083fa2_1
    - tomli 2.0.2 pyhd8ed1ab_0
    - typing-extensions 4.12.2 hd8ed1ab_0
    - typing_extensions 4.12.2 pyha770c72_0
    - tzdata 2024b hc8b5060_0
    - wheel 0.45.0 pyhd8ed1ab_0
    - xz 5.2.6 h57fd34a_0
  run:
    - python >=3.12,<3.13.0a0
    - python >=3.12,<3.13.0a0 *_cpython
    - python_abi 3.12.* *_cp312
test:
  commands:
    - SP_DIR="$(python -c 'import site; print(site.getsitepackages()[0])')"
    - test -f "${SP_DIR}/menuinst/data/appkit_launcher_arm64"
    - test -f "${SP_DIR}/menuinst/data/appkit_launcher_x86_64"
    - test -f "${SP_DIR}/menuinst/data/osx_launcher_arm64"
    - test -f "${SP_DIR}/menuinst/data/osx_launcher_x86_64"
  imports:
    - menuinst
    - menuinst.api
about:
  doc_url: https://conda.github.io/menuinst/
  home: https://github.com/conda/menuinst/
  license: BSD-3-Clause AND MIT
  license_file:
    - LICENSE.txt
    - menuinst/_vendor/apipkg/LICENSE
  summary: cross platform install of menu items
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20241109.1.1
  recipe-maintainers:
    - carlodri
    - goanpeca
    - isuruf
    - jaimergp
    - jakirkham
  remote_url: https://github.com/conda-forge/menuinst-feedstock
  sha: 9c36347356d4b8a2a1c3c5854dba1f96a2438dd6
