# This file created by conda-build 24.7.1
# ------------------------------------------------

package:
  name: brotli-python
  version: 1.1.0
source:
  fn: brotli-1.1.0.tar.gz
  sha256: e720a6ca29428b803f4ad165371771f5398faba397edf6778837a18599ea13ff
  url: https://github.com/google/brotli/archive/v1.1.0.tar.gz
build:
  ignore_run_exports_from:
    - brotli
  number: 2
  string: py312hde4cb15_2
requirements:
  build:
    - bzip2 1.0.8 hfdf4475_7
    - c-ares 1.33.1 h44e7173_0
    - ca-certificates 2024.8.30 h8857fd0_0
    - cctools_osx-64 986 h0282933_3
    - cctools_osx-arm64 986 h5660759_3
    - clang 17.0.6 default_he371ed4_6
    - clang-17 17.0.6 default_hb173f14_6
    - clang_impl_osx-arm64 17.0.6 h840ab8d_19
    - clang_osx-arm64 17.0.6 h40be2b1_19
    - clangxx 17.0.6 default_he371ed4_6
    - clangxx_impl_osx-arm64 17.0.6 ha3b5c75_19
    - clangxx_osx-arm64 17.0.6 h40be2b1_19
    - cmake 3.30.3 h7243fc2_0
    - compiler-rt 17.0.6 h1020d70_2
    - compiler-rt_osx-64 17.0.6 hf2b8a54_2
    - cross-python_osx-arm64 3.12 42_cpython
    - crossenv 1.4.0 pyhd8ed1ab_0
    - gettext 0.22.5 hdfe23c8_3
    - gettext-tools 0.22.5 hdfe23c8_3
    - icu 75.1 h120a0e1_0
    - krb5 1.21.3 h37d8d59_0
    - ld64_osx-64 711 hf158dd0_3
    - ld64_osx-arm64 711 haa85353_3
    - libasprintf 0.22.5 hdfe23c8_3
    - libasprintf-devel 0.22.5 hdfe23c8_3
    - libclang-cpp17 17.0.6 default_hb173f14_6
    - libcurl 8.9.1 hfcf2730_0
    - libcxx 18.1.8 hd876a4e_6
    - libcxx-devel 18.1.8 h7c275be_6
    - libedit 3.1.20191231 h0678c8f_2
    - libev 4.33 h10d778d_2
    - libexpat 2.6.2 h73e2aa4_0
    - libffi 3.4.2 h0d85af4_5
    - libgettextpo 0.22.5 hdfe23c8_3
    - libgettextpo-devel 0.22.5 hdfe23c8_3
    - libiconv 1.17 hd75f5a5_2
    - libintl 0.22.5 hdfe23c8_3
    - libintl-devel 0.22.5 hdfe23c8_3
    - libllvm17 17.0.6 hbedff68_1
    - libnghttp2 1.58.0 h64cf6d3_1
    - libsqlite 3.46.0 h1b8f9f3_0
    - libssh2 1.11.0 hd019ec5_0
    - libuv 1.48.0 h67532ce_0
    - libxml2 2.12.7 heaf3512_4
    - libzlib 1.3.1 h87427d6_1
    - llvm-tools 17.0.6 hbedff68_1
    - lz4-c 1.9.4 hf0c8a7f_0
    - macosx_deployment_target_osx-arm64 11.0 h6553868_1
    - ncurses 6.5 hf036a51_1
    - ninja 1.12.1 h3c5361c_0
    - openssl 3.3.1 hd23fc13_3
    - popt 1.16 h7b079dc_2002
    - python 3.12.5 h37a9e06_0_cpython
    - readline 8.2 h9e318b2_1
    - rhash 1.4.4 h0dc2134_0
    - rsync 3.3.0 h5aaac6a_0
    - sed 4.7 h3efe00b_1000
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - tk 8.6.13 h1abcd95_1
    - tzdata 2024a h8827d51_1
    - xxhash 0.8.2 h4140336_0
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.6 h915ae27_0
  host:
    - brotli 1.1.0 hd74edd7_2
    - bzip2 1.0.8 h99b78c6_7
    - ca-certificates 2024.8.30 hf0a4a13_0
    - libcxx 18.1.8 h3ed4263_6
    - libexpat 2.6.2 hebf3989_0
    - libffi 3.4.2 h3422bc3_5
    - libsqlite 3.46.0 hfb93653_0
    - libzlib 1.3.1 hfb2fe0b_1
    - ncurses 6.5 h7bae524_1
    - openssl 3.3.1 h8359307_3
    - pip 24.2 pyh8b19718_1
    - python 3.12.5 h30c5eda_0_cpython
    - readline 8.2 h92ec313_1
    - setuptools 72.2.0 pyhd8ed1ab_0
    - tk 8.6.13 h5083fa2_1
    - tzdata 2024a h8827d51_1
    - wheel 0.44.0 pyhd8ed1ab_0
    - xz 5.2.6 h57fd34a_0
  run:
    - __osx >=11.0
    - libcxx >=17
    - python >=3.12,<3.13.0a0
    - python >=3.12,<3.13.0a0 *_cpython
    - python_abi 3.12.* *_cp312
  run_constrained:
    - libbrotlicommon 1.1.0 hd74edd7_2
test:
  imports:
    - brotli
about:
  home: http://github.com/google/brotli
  license: MIT
  license_file: LICENSE
  summary: Brotli compression format
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240902.3.1
  recipe-maintainers:
    - CJ-Wright
    - wesm
    - xhochy
  remote_url: https://github.com/conda-forge/brotli-feedstock
  sha: c6b8e904902e82f888f50e4ca6f23390d784ce79
