# This file created by conda-build 25.1.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Feb 27 10:57:36 2025
# ------------------------------------------------

package:
  name: setuptools
  version: 75.8.2
source:
  patches:
    - patches/0021-Add-d1trimfile-SRC_DIR-to-make-pdbs-more-relocatable.patch
  sha256: 4880473a969e5f23f2a2be3646b2dfd84af9028716d398e46192f84bc36900d2
  url: https://pypi.org/packages/source/s/setuptools/setuptools-75.8.2.tar.gz
build:
  noarch: python
  number: '0'
  string: pyhff2d567_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h4bc722e_7
    - ca-certificates 2025.1.31 hbcca054_0
    - ld_impl_linux-64 2.43 h712a8e2_4
    - libffi 3.4.6 h2dba641_0
    - libgcc 14.2.0 h767d61c_2
    - libgcc-ng 14.2.0 h69a702a_2
    - libgomp 14.2.0 h767d61c_2
    - liblzma 5.6.4 hb9d3cd8_0
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.49.1 hee588c1_1
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 hb9d3cd8_2
    - ncurses 6.5 h2d0b736_3
    - openssl 3.4.1 h7b32b05_0
    - python 3.9.21 h9c0c6dc_1_cpython
    - readline 8.2 h8c095d6_2
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2025a h78e105d_0
  run:
    - python >=3.9
test:
  imports:
    - pkg_resources
    - setuptools
  requires:
    - python
about:
  description: 'Setuptools is a fully-featured, actively-maintained, and stable library

    designed to facilitate packaging Python projects.

    '
  dev_url: https://github.com/pypa/setuptools
  doc_source_url: https://github.com/pypa/setuptools/tree/master/docs
  doc_url: http://pythonhosted.org/setuptools/
  home: https://github.com/pypa/setuptools
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Download, build, install, upgrade, and uninstall Python packages
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20250227.1.1
  recipe-maintainers:
    - isuruf
    - jakirkham
    - msarahan
    - nicoddemus
    - ocefpaf
    - rgommers
    - xhochy
  remote_url: https://github.com/conda-forge/setuptools-feedstock
  sha: 66dcc5d189336642efd1840d848ed91c570a8db2
