# This file created by conda-build 24.7.1
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Mon Sep  2 19:30:30 2024
# ------------------------------------------------

package:
  name: zstandard
  version: 0.23.0
source:
  sha256: b2d8c62d08e7255f68f7a740bae85b3c9b8e5466baa9cbf7f57f1cde0ac6bc09
  url: https://pypi.io/packages/source/z/zstandard/zstandard-0.23.0.tar.gz
build:
  number: '1'
  string: py312h15fbf35_1
requirements:
  build:
    - bzip2 1.0.8 hfdf4475_7
    - ca-certificates 2024.8.30 h8857fd0_0
    - cctools_osx-64 986 h0282933_3
    - cctools_osx-arm64 986 h5660759_3
    - cffi 1.17.0 py312hf857d28_1
    - clang 17.0.6 default_he371ed4_6
    - clang-17 17.0.6 default_hb173f14_6
    - clang_impl_osx-arm64 17.0.6 h840ab8d_19
    - clang_osx-arm64 17.0.6 h40be2b1_19
    - clangxx 17.0.6 default_he371ed4_6
    - compiler-rt 17.0.6 h1020d70_2
    - compiler-rt_osx-64 17.0.6 hf2b8a54_2
    - cross-python_osx-arm64 3.12 42_cpython
    - crossenv 1.4.0 pyhd8ed1ab_0
    - gettext 0.22.5 hdfe23c8_3
    - gettext-tools 0.22.5 hdfe23c8_3
    - icu 75.1 h120a0e1_0
    - ld64_osx-64 711 hf158dd0_3
    - ld64_osx-arm64 711 haa85353_3
    - libasprintf 0.22.5 hdfe23c8_3
    - libasprintf-devel 0.22.5 hdfe23c8_3
    - libclang-cpp17 17.0.6 default_hb173f14_6
    - libcxx 18.1.8 hd876a4e_6
    - libcxx-devel 18.1.8 h7c275be_6
    - libexpat 2.6.2 h73e2aa4_0
    - libffi 3.4.2 h0d85af4_5
    - libgettextpo 0.22.5 hdfe23c8_3
    - libgettextpo-devel 0.22.5 hdfe23c8_3
    - libiconv 1.17 hd75f5a5_2
    - libintl 0.22.5 hdfe23c8_3
    - libintl-devel 0.22.5 hdfe23c8_3
    - libllvm17 17.0.6 hbedff68_1
    - libsqlite 3.46.0 h1b8f9f3_0
    - libxml2 2.12.7 heaf3512_4
    - libzlib 1.3.1 h87427d6_1
    - llvm-tools 17.0.6 hbedff68_1
    - lz4-c 1.9.4 hf0c8a7f_0
    - macosx_deployment_target_osx-arm64 11.0 h6553868_1
    - ncurses 6.5 hf036a51_1
    - openssl 3.3.1 hd23fc13_3
    - popt 1.16 h7b079dc_2002
    - pycparser 2.22 pyhd8ed1ab_0
    - python 3.12.5 h37a9e06_0_cpython
    - python_abi 3.12 5_cp312
    - readline 8.2 h9e318b2_1
    - rsync 3.3.0 h5aaac6a_0
    - sed 4.7 h3efe00b_1000
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - tk 8.6.13 h1abcd95_1
    - tzdata 2024a h8827d51_1
    - xxhash 0.8.2 h4140336_0
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.6 h915ae27_0
  host:
    - bzip2 1.0.8 h99b78c6_7
    - ca-certificates 2024.8.30 hf0a4a13_0
    - cffi 1.17.0 py312h0fad829_1
    - libexpat 2.6.2 hebf3989_0
    - libffi 3.4.2 h3422bc3_5
    - libsqlite 3.46.0 hfb93653_0
    - libzlib 1.3.1 hfb2fe0b_1
    - ncurses 6.5 h7bae524_1
    - openssl 3.3.1 h8359307_3
    - pip 24.2 pyh8b19718_1
    - pycparser 2.22 pyhd8ed1ab_0
    - python 3.12.5 h30c5eda_0_cpython
    - python_abi 3.12 5_cp312
    - readline 8.2 h92ec313_1
    - setuptools 72.2.0 pyhd8ed1ab_0
    - tk 8.6.13 h5083fa2_1
    - tzdata 2024a h8827d51_1
    - wheel 0.44.0 pyhd8ed1ab_0
    - xz 5.2.6 h57fd34a_0
    - zstd 1.5.6 hb46c0d2_0
  run:
    - __osx >=11.0
    - cffi >=1.11
    - python >=3.12,<3.13.0a0
    - python >=3.12,<3.13.0a0 *_cpython
    - python_abi 3.12.* *_cp312
    - zstd >=1.5.6,<1.5.7.0a0
    - zstd >=1.5.6,<1.6.0a0
test:
  commands:
    - pip check
  imports:
    - zstandard
  requires:
    - pip
about:
  description: 'This project provides Python bindings for interfacing with the

    Zstandard compression library. A C extension and CFFI interface are

    provided.

    '
  dev_url: https://github.com/indygreg/python-zstandard
  doc_url: https://github.com/indygreg/python-zstandard/blob/master/README.rst#python-zstandard
  home: https://github.com/indygreg/python-zstandard
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Zstandard bindings for Python
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240902.3.1
  recipe-maintainers:
    - pavelzw
    - rmax
    - xhochy
  remote_url: https://github.com/conda-forge/zstandard-feedstock
  sha: 2894dec506a78515d0a7a4fc8914910be70deb10
