# This file created by conda-build 24.11.2
# ------------------------------------------------

package:
  name: mamba
  version: 1.5.12
source:
  sha256: 9549cf7708dae3331e36ca5103db635481ed0660f580058a492114ce2ab9a831
  url: https://github.com/mamba-org/mamba/archive/refs/tags/2025.01.02.tar.gz
build:
  entry_points:
    - mamba = mamba.mamba:main
  number: 0
  string: py312h14bc7db_0
requirements:
  build:
    - bzip2 1.0.8 hfdf4475_7
    - ca-certificates 2024.12.14 h8857fd0_0
    - cctools_osx-64 1010.6 hadbd6bd_2
    - cctools_osx-arm64 1010.6 h563b5bc_2
    - clang 19.1.6 default_h576c50e_0
    - clang-19 19.1.6 default_h3571c67_0
    - clang_impl_osx-arm64 19.1.6 h252a79b_23
    - clang_osx-arm64 19.1.6 h1728699_23
    - clangxx 19.1.6 default_heb2e8d1_0
    - clangxx_impl_osx-arm64 19.1.6 hb1f5f5c_23
    - compiler-rt 19.1.6 h52031e2_0
    - compiler-rt_osx-64 19.1.6 hc6f8467_0
    - cross-python_osx-arm64 3.12 50_cpython
    - crossenv 1.5.0 pyhd8ed1ab_1
    - gettext 0.22.5 hdfe23c8_3
    - gettext-tools 0.22.5 hdfe23c8_3
    - ld64_osx-64 951.9 h9d2de3d_2
    - ld64_osx-arm64 951.9 hdfa8970_2
    - libasprintf 0.22.5 hdfe23c8_3
    - libasprintf-devel 0.22.5 hdfe23c8_3
    - libclang-cpp19.1 19.1.6 default_h3571c67_0
    - libcxx 19.1.6 hf95d169_1
    - libcxx-devel 19.1.6 h7c275be_1
    - libexpat 2.6.4 h240833e_0
    - libffi 3.4.2 h0d85af4_5
    - libgettextpo 0.22.5 hdfe23c8_3
    - libgettextpo-devel 0.22.5 hdfe23c8_3
    - libiconv 1.17 hd75f5a5_2
    - libintl 0.22.5 hdfe23c8_3
    - libintl-devel 0.22.5 hdfe23c8_3
    - libllvm19 19.1.6 hc29ff6c_0
    - liblzma 5.6.3 hd471939_1
    - libsqlite 3.47.2 hdb6dae5_0
    - libxml2 2.13.5 he8ee3e7_1
    - libzlib 1.3.1 hd23fc13_2
    - llvm-tools 19.1.6 h3fe3016_0
    - llvm-tools-19 19.1.6 he90a8e3_0
    - lz4-c 1.10.0 h240833e_1
    - ncurses 6.5 hf036a51_1
    - openssl 3.4.0 hd471939_0
    - popt 1.16 h7b079dc_2002
    - python 3.12.8 h9ccd52b_1_cpython
    - readline 8.2 h9e318b2_1
    - rsync 3.3.0 hbf82b91_1
    - sed 4.7 h3efe00b_1000
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1300.6.5 h390ca13_0
    - tk 8.6.13 h1abcd95_1
    - tzdata 2024b hc8b5060_0
    - xxhash 0.8.2 h4140336_0
    - zstd 1.5.6 h915ae27_0
  host:
    - bzip2 1.0.8 h99b78c6_7
    - ca-certificates 2024.12.14 hf0a4a13_0
    - libexpat 2.6.4 h286801f_0
    - libffi 3.4.2 h3422bc3_5
    - liblzma 5.6.3 h39f12f2_1
    - libmambapy 1.5.12 py312h86ad8a2_0
    - libsqlite 3.47.2 h3f77e49_0
    - libzlib 1.3.1 h8359307_2
    - ncurses 6.5 h7bae524_1
    - openssl 3.4.0 h39f12f2_0
    - pip 24.3.1 pyh8b19718_2
    - python 3.12.8 hc22306f_1_cpython
    - readline 8.2 h92ec313_1
    - setuptools 75.6.0 pyhff2d567_1
    - tk 8.6.13 h5083fa2_1
    - tzdata 2024b hc8b5060_0
    - wheel 0.45.1 pyhd8ed1ab_1
  run:
    - conda >=24,<25
    - libmambapy 1.5.12 py312h86ad8a2_0
    - openssl >=3.4.0,<4.0a0
    - python >=3.12,<3.13.0a0
    - python >=3.12,<3.13.0a0 *_cpython
    - python_abi 3.12.* *_cp312
test:
  commands:
    - mamba --help
    - mamba create -n test_py2 python=2.7 --dry-run
    - mamba clean --all --dry-run
    - mamba repoquery whoneeds conda
    - python -c "import mamba._version; assert mamba._version.__version__ == '1.5.12'"
    - test -f ${PREFIX}/condabin/mamba
  imports:
    - mamba
  requires:
    - pip
about:
  description: '


    [![Build Status](https://github.com/mamba-org/mamba/workflows/CI/badge.svg)](https://github.com/mamba-org/mamba/actions)

    [![Join the Gitter Chat](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/mamba-org/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

    [![docs](https://readthedocs.org/projects/mamba/badge/?version=latest&style=flat)](https://mamba.readthedocs.io/en/latest)


    `mamba` is a reimplementation of the conda package manager in C++.


    - parallel downloading of repository data and package files using multi-threading

    - libsolv for much faster dependency solving, a state of the art library used
    in the RPM package manager of Red Hat, Fedora and OpenSUSE

    - core parts of `mamba` are implemented in C++ for maximum efficiency


    At the same time, `mamba` utilizes the same command line parser, package installation
    and deinstallation code and transaction verification routines as `conda` to stay
    as compatible as possible.


    Mamba is part of a bigger ecosystem to make scientific packaging more sustainable.
    You can read our [announcement blog post](https://medium.com/@QuantStack/open-software-packaging-for-science-61cecee7fc23).

    The ecosystem also consists of `quetz`, an open source `conda` package server
    and `boa`, a fast `conda` package builder.




    Please refer to the [`mamba` and `micromamba` installation guide](https://mamba.readthedocs.io/en/latest/installation.html)
    in the documentation.




    `mamba` and `micromamba` come with features on top of stock `conda`.




    To efficiently query repositories and query package dependencies you can use `mamba
    repoquery` or `micromamba repoquery`.

    See the [repoquery documentation](https://mamba.readthedocs.io/en/latest/user_guide/mamba.html#repoquery)
    for details.




    `micromamba` can be used to install lock files generated by [conda-lock](https://conda-incubator.github.io/conda-lock/)
    without having to install `conda-lock`. Simply invoke e.g. `micromamba create
    -n my-env -f conda-lock.yml` with an environment lockfile named `*-lock.yml` or
    `*-lock.yaml`.

    '
  dev_url: https://github.com/mamba-org/mamba
  home: https://github.com/mamba-org/mamba
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A fast drop-in alternative to conda, using libsolv for dependency resolution
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20250102.6.1
  recipe-maintainers:
    - AntoinePrv
    - JohanMabille
    - SylvainCorlay
    - adriendelsalle
    - ericmjl
    - wolfv
  remote_url: https://github.com/conda-forge/mamba-feedstock
  sha: e1e542e2e7c74bcda7fab6c2a8c703803ed92af2
