# This file created by conda-build 24.11.2
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Mon Dec  9 10:39:44 2024
# ------------------------------------------------

package:
  name: lz4-c
  version: 1.10.0
source:
  sha256: 537512904744b35e232912055ccf8ec66d768639ff3abe5788d90d792ec5f48b
  url: https://github.com/lz4/lz4/archive/v1.10.0.tar.gz
build:
  number: '1'
  run_exports:
    - lz4-c >=1.10.0,<1.11.0a0
  string: h286801f_1
requirements:
  build:
    - ca-certificates 2024.8.30 h8857fd0_0
    - cctools_osx-64 1010.6 h00edd4c_2
    - cctools_osx-arm64 1010.6 h71f0a72_2
    - clang 18.1.8 default_h179603d_5
    - clang-18 18.1.8 default_h0c94c6a_5
    - clang_impl_osx-arm64 18.1.8 hadf8e89_23
    - clang_osx-arm64 18.1.8 h1728699_23
    - clangxx 18.1.8 default_h179603d_5
    - clangxx_impl_osx-arm64 18.1.8 hd2305f4_23
    - clangxx_osx-arm64 18.1.8 h1728699_23
    - compiler-rt 18.1.8 h1020d70_1
    - compiler-rt_osx-64 18.1.8 hf2b8a54_1
    - ld64_osx-64 951.9 hc8d1a19_2
    - ld64_osx-arm64 951.9 h148c8d5_2
    - libclang-cpp18.1 18.1.8 default_h0c94c6a_5
    - libcxx 19.1.5 hf95d169_0
    - libcxx-devel 18.1.8 h7c275be_7
    - libiconv 1.17 hd75f5a5_2
    - libllvm18 18.1.8 h9ce406d_2
    - liblzma 5.6.3 hd471939_1
    - libxml2 2.13.5 he8ee3e7_1
    - libzlib 1.3.1 hd23fc13_2
    - llvm-tools 18.1.8 h9ce406d_2
    - llvm-tools-18 18.1.8 h9ce406d_2
    - macosx_deployment_target_osx-arm64 11.0 h6553868_2
    - make 4.4.1 h00291cd_2
    - ncurses 6.5 hf036a51_1
    - openssl 3.4.0 hd471939_0
    - patch 2.7.6 hbcf498f_1002
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1300.6.5 h390ca13_0
    - zstd 1.5.6 h915ae27_0
  host:
    - libcxx 19.1.5 ha82da77_0
  run:
    - __osx >=11.0
    - libcxx >=18
about:
  description: 'LZ4 is lossless compression algorithm, providing compression speed
    at 400

    MB/s per core (0.16 Bytes/cycle). It features an extremely fast decoder,

    with speed in multiple GB/s per core (0.71 Bytes/cycle). A high compression

    derivative, called LZ4_HC, is available, trading customizable CPU time for

    compression ratio. LZ4 library is provided as open source software using a

    BSD license.

    '
  dev_url: https://github.com/lz4/lz4
  home: https://www.lz4.org
  license: BSD-2-Clause
  license_file: lib/LICENSE
  summary: Extremely Fast Compression algorithm
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20241209.2.1
  recipe-maintainers:
    - mingwandroid
    - rmax
    - wesm
    - xhochy
  remote_url: https://github.com/conda-forge/lz4-c-feedstock
  sha: 1771aeaed9cf4d91619cee1e822416b03e429f54
