# This file created by conda-build 25.1.1
# ------------------------------------------------

package:
  name: liblzma
  version: 5.6.4
source:
  sha256: 269e3f2e512cbd3314849982014dc199a7b2148cf5c91cedc6db629acdf5e09b
  url: https://github.com/tukaani-project/xz/releases/download/v5.6.4/xz-5.6.4.tar.gz
build:
  number: 0
  run_exports:
    - liblzma >=5.6.4,<6.0a0
  string: h39f12f2_0
requirements:
  build:
    - clang_bootstrap_osx-arm64 18.1.8 hf1725c4_23
    - macosx_deployment_target_osx-arm64 11.0 h6553868_2
    - make 4.4.1 h00291cd_2
  host:
    - __osx >=11.0
  run:
    - __osx >=11.0
test:
  commands:
    - test ! -f ${PREFIX}/lib/liblzma.a
    - test ! -f ${PREFIX}/lib/liblzma${SHLIB_EXT}
    - test -f ${PREFIX}/lib/liblzma.*.dylib
about:
  license: 0BSD
  license_file:
    - COPYING
    - COPYING.0BSD
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20250202.1.1
  recipe-maintainers:
    - mingwandroid
    - msarahan
    - nehaljwani
    - ocefpaf
    - scopatz
    - xhochy
  remote_url: https://github.com/conda-forge/xz-feedstock
  sha: 11e09789c398d79dd6507ff7ceea5ac81eb56190
