CI: azure
CONDA_BUILD_SYSROOT: /Applications/Xcode_15.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk
MACOSX_DEPLOYMENT_TARGET: '11.0'
MACOSX_SDK_VERSION: '11.0'
build_platform: osx-64
bzip2: '1'
c_compiler: clang
c_compiler_version: '18'
c_stdlib: macosx_deployment_target
c_stdlib_version: '11.0'
channel_sources: conda-forge
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: clangxx
extend_keys:
- pin_run_as_build
- extend_keys
- ignore_build_only_deps
- ignore_version
fortran_compiler: gfortran
ignore_build_only_deps:
- numpy
- python
libarchive: '3.7'
libiconv: '1'
liblzma_devel: '5'
libxml2: '2'
lua: '5'
lz4_c: '1.10'
lzo: '2'
macos_machine: arm64-apple-darwin20.0.0
numpy: '1.26'
openssl: '3'
perl: 5.26.2
pin_run_as_build:
  python:
    max_pin: x.x
    min_pin: x.x
  r-base:
    max_pin: x.x
    min_pin: x.x
python: '3.12'
r_base: '3.5'
target_platform: osx-arm64
zlib: '1'
zstd: '1.5'
