#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PYTHON_SCRIPT="$SCRIPT_DIR/analyze_frametime.py"
PYTHON_BIN="$SCRIPT_DIR/python/miniforge3/bin/python3

CSV_EXPORT_PATH="$1"
MULTITHREAD_FLAG="$2"

if [ -z "$1" ]; then
  echo "❌ No video file provided."
  exit 1
fi

"$PYTHON_BIN" "$PYTHON_SCRIPT" "$3" "$CSV_EXPORT_PATH" "$MULTITHREAD_FLAG"
