# This file created by conda-build 25.1.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri Feb 14 06:49:28 2025
# ------------------------------------------------

package:
  name: certifi
  version: 2025.1.31
source:
  - folder: certifi
    sha256: 3d5da6925056f6f18f119200434a4780a94263f10d1c21d032a6f6b2baa20651
    url: https://pypi.org/packages/source/c/certifi/certifi-2025.1.31.tar.gz
  - folder: boostrap_wheels
    sha256: c46efd13b6aa8279f33f2864459c8ce587ea6a1a59ee20de055868d8f7688f7f
    url: https://pypi.org/packages/py3/p/pip/pip-25.0.1-py3-none-any.whl
  - folder: boostrap_wheels
    sha256: e3982f444617239225d675215d51f6ba05f845d4eec313da4418fdbb56fb27e3
    url: https://pypi.org/packages/py3/s/setuptools/setuptools-75.8.0-py3-none-any.whl
  - folder: boostrap_wheels
    sha256: 708e7481cc80179af0e556bbf0cc00b8444c7321e2700b8d8580231d13017248
    url: https://pypi.org/packages/py3/w/wheel/wheel-0.45.1-py3-none-any.whl
build:
  noarch: python
  number: '0'
  script:
    - cd certifi
    - /home/conda/feedstock_root/build_artifacts/certifi_1739515848642/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
      -m pip install . -vv
  script_env:
    - 'PYTHONPATH=/home/conda/feedstock_root/build_artifacts/certifi_1739515848642/work/boostrap_wheels:'
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h4bc722e_7
    - ca-certificates 2025.1.31 hbcca054_0
    - ld_impl_linux-64 2.43 h712a8e2_2
    - libffi 3.4.6 h2dba641_0
    - libgcc 14.2.0 h77fa898_1
    - libgcc-ng 14.2.0 h69a702a_1
    - libgomp 14.2.0 h77fa898_1
    - liblzma 5.6.4 hb9d3cd8_0
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.48.0 hee588c1_1
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 hb9d3cd8_2
    - ncurses 6.5 h2d0b736_3
    - openssl 3.4.1 h7b32b05_0
    - python 3.9.21 h9c0c6dc_1_cpython
    - readline 8.2 h8228510_1
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2025a h78e105d_0
  run:
    - python >=3.9
test:
  imports:
    - certifi
  requires:
    - python 3.9.*
about:
  description: 'Certifi is a curated collection of Root Certificates for validating
    the

    trustworthiness of SSL certificates while verifying the identity of TLS

    hosts.

    '
  dev_url: https://github.com/certifi/python-certifi
  doc_source_url: https://github.com/certifi/certifi.io/blob/master/README.rst
  doc_url: https://pypi.python.org/pypi/certifi
  home: http://certifi.io/
  license: ISC
  license_file: certifi/LICENSE
  summary: Python package for providing Mozilla's CA Bundle.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20250214.4.1
  recipe-maintainers:
    - jakirkham
    - ocefpaf
    - pelson
    - sigmavirus24
  remote_url: https://github.com/conda-forge/certifi-feedstock
  sha: 518e94ee8c2bfd15c2fb5fc3507b6e61ccc1c2b5
