# This file created by conda-build 3.28.1
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Sat Dec  9 18:19:10 2023
# ------------------------------------------------

package:
  name: libev
  version: '4.33'
source:
  sha256: 507eb7b8d1015fbec5b935f34ebed15bf346bed04a11ab82b8eee848c4205aea
  url: http://dist.schmorp.de/libev/Attic/libev-4.33.tar.gz
build:
  number: '2'
  run_exports:
    - libev >=4.33,<4.34.0a0
  string: h93a5062_2
requirements:
  build:
    - ca-certificates 2023.11.17 h8857fd0_0
    - cctools_osx-64 973.0.1 ha1c5b94_15
    - cctools_osx-arm64 973.0.1 h7bb7a8e_15
    - clang 16.0.6 hac416ee_3
    - clang-16 16.0.6 default_h6b1ee41_3
    - clang_impl_osx-arm64 16.0.6 ha81d56d_6
    - clang_osx-arm64 16.0.6 h40be2b1_6
    - clangxx 16.0.6 default_h6b1ee41_3
    - compiler-rt 16.0.6 ha38d28d_2
    - compiler-rt_osx-64 16.0.6 ha38d28d_2
    - icu 73.2 hf5e326d_0
    - ld64_osx-64 609 ha20a434_15
    - ld64_osx-arm64 609 h6aa3cc8_15
    - libclang-cpp16 16.0.6 default_h6b1ee41_3
    - libcxx 16.0.6 hd57cbcb_0
    - libiconv 1.17 hac89ed1_0
    - libllvm16 16.0.6 hbedff68_3
    - libtool 2.4.7 hf0c8a7f_0
    - libxml2 2.12.2 hc0ae0f7_0
    - libzlib 1.2.13 h8a1eda9_5
    - llvm-tools 16.0.6 hbedff68_3
    - make 4.3 h22f3db7_1
    - openssl 3.2.0 hd75f5a5_1
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.5 h829000d_0
  host: []
  run: []
about:
  home: http://software.schmorp.de/pkg/libev.html
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A full-featured and high-performance event loop that is loosely modeled
    after libevent, but without its limitations and bugs.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20231209.1.1
  recipe-maintainers:
    - carlodri
    - petercable
    - wolfv
  remote_url: https://github.com/conda-forge/libev-feedstock
  sha: a012320b04376463b1f00539ea714688da15c24b
