# This file created by conda-build 25.1.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Jan 23 07:44:29 2025
# ------------------------------------------------

package:
  name: hyperframe
  version: 6.1.0
source:
  fn: hyperframe-6.1.0.tar.gz
  sha256: f630908a00854a7adeabd6382b43923a4c4cd4b821fcb527e6ab9e15382a3b08
  url: https://pypi.org/packages/source/h/hyperframe/hyperframe-6.1.0.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/hyperframe_1737618333194/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python
    -m pip install . -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h4bc722e_7
    - ca-certificates 2024.12.14 hbcca054_0
    - ld_impl_linux-64 2.43 h712a8e2_2
    - libffi 3.4.2 h7f98852_5
    - libgcc 14.2.0 h77fa898_1
    - libgcc-ng 14.2.0 h69a702a_1
    - libgomp 14.2.0 h77fa898_1
    - liblzma 5.6.3 hb9d3cd8_1
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.48.0 hee588c1_1
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 hb9d3cd8_2
    - ncurses 6.5 h2d0b736_2
    - openssl 3.4.0 h7b32b05_1
    - pip 24.3.1 pyh8b19718_2
    - python 3.9.21 h9c0c6dc_1_cpython
    - readline 8.2 h8228510_1
    - setuptools 75.8.0 pyhff2d567_0
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2025a h78e105d_0
    - wheel 0.45.1 pyhd8ed1ab_1
  run:
    - python >=3.9
test:
  imports:
    - hyperframe
  requires:
    - python 3.9.*
about:
  dev_url: https://github.com/python-hyper/hyperframe
  home: http://python-hyper.org/hyperframe/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Pure-Python HTTP/2 framing '
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20250123.1.1
  recipe-maintainers:
    - astaric
    - primozgodec
  remote_url: https://github.com/conda-forge/hyperframe-feedstock
  sha: 1bd056568c400d11a82be3f3fe665fda329aa581
