# This file created by conda-build 25.1.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Mar 10 15:31:06 2025
# ------------------------------------------------

package:
  name: conda-package-streaming
  version: 0.11.0
source:
  sha256: 407ec0bd3f65fccc3ac8e02f7ba3bb31c95ceca10ebdcfe66120bf56db28e59b
  url: https://github.com/conda/conda-package-streaming/archive/refs/tags/v0.11.0.tar.gz
build:
  noarch: python
  number: '1'
  script: /home/conda/feedstock_root/build_artifacts/conda-package-streaming_1741620732069/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/python
    -m pip install --no-build-isolation . -vv
  string: pyhd8ed1ab_1
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h4bc722e_7
    - ca-certificates 2025.1.31 hbcca054_0
    - flit-core 3.11.0 pyhd8ed1ab_0
    - ld_impl_linux-64 2.43 h712a8e2_4
    - libffi 3.4.6 h2dba641_0
    - libgcc 14.2.0 h767d61c_2
    - libgcc-ng 14.2.0 h69a702a_2
    - libgomp 14.2.0 h767d61c_2
    - liblzma 5.6.4 hb9d3cd8_0
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.49.1 hee588c1_1
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 hb9d3cd8_2
    - ncurses 6.5 h2d0b736_3
    - openssl 3.4.1 h7b32b05_0
    - pip 25.0.1 pyh8b19718_0
    - python 3.9.21 h9c0c6dc_1_cpython
    - readline 8.2 h8c095d6_2
    - setuptools 75.8.2 pyhff2d567_0
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2025a h78e105d_0
    - wheel 0.45.1 pyhd8ed1ab_1
  run:
    - python >=3.9
    - zstandard >=0.15
test:
  commands:
    - pip check
  imports:
    - conda_package_streaming.url
  requires:
    - pip
    - python 3.9.*
    - requests
about:
  dev_url: https://github.com/conda/conda-package-streaming
  doc_url: https://conda.github.io/conda-package-streaming/
  home: https://github.com/conda/conda-package-streaming
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Download metadata from conda packages without transferring entire file.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20250310.1.1
  recipe-maintainers:
    - dholth
  remote_url: https://github.com/conda-forge/conda-package-streaming-feedstock
  sha: fc3487628e30485dc88f4b830ebc2ed1f70c2d92
