# This file created by conda-build 24.9.0
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Sat Oct 12 09:13:14 2024
# ------------------------------------------------

package:
  name: ruamel.yaml.clib
  version: 0.2.8
source:
  - sha256: beb2e0404003de9a4cab9753a8805a8fe9320ee6673136ed7f04255fe60bb512
    url: https://pypi.io/packages/source/r/ruamel.yaml.clib/ruamel.yaml.clib-0.2.8.tar.gz
  - fn: _ruamel_yaml.pyx
    patches:
      - fix-typecasts-s390x._ruamel_yaml.pyx.patch
    sha256: fb6b5653201f1ed89a951f6931fda377737156c4f30cadbd240f4d28f607665a
    url: https://sourceforge.net/p/ruamel-yaml-clib/code/ci/0.2.8/tree/_ruamel_yaml.pyx?format=raw
  - fn: _ruamel_yaml.pxd
    patches:
      - fix-typecasts-s390x._ruamel_yaml.pxd.patch
    sha256: ee35a75fd753a369bee439ec7e1826e77c7feaabf9c3ec9cf2f58110c7a95656
    url: https://sourceforge.net/p/ruamel-yaml-clib/code/ci/0.2.8/tree/_ruamel_yaml.pxd?format=raw
build:
  number: '1'
  script:
    - cythonize _ruamel_yaml.pyx
    - /Users/runner/miniforge3/conda-bld/ruamel.yaml.clib_1728724504988/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
      -m pip install . -vv
  string: py312h0bf5046_1
requirements:
  build:
    - bzip2 1.0.8 hfdf4475_7
    - ca-certificates 2024.8.30 h8857fd0_0
    - cctools_osx-64 1010.6 h98e843e_1
    - cctools_osx-arm64 1010.6 h7a13591_1
    - clang 17.0.6 default_he371ed4_7
    - clang-17 17.0.6 default_hb173f14_7
    - clang_impl_osx-arm64 17.0.6 h840ab8d_21
    - clang_osx-arm64 17.0.6 h40be2b1_21
    - clangxx 17.0.6 default_he371ed4_7
    - clangxx_impl_osx-arm64 17.0.6 ha3b5c75_21
    - compiler-rt 17.0.6 h1020d70_2
    - compiler-rt_osx-64 17.0.6 hf2b8a54_2
    - cross-python_osx-arm64 3.12 50_cpython
    - crossenv 1.5.0 pyhd8ed1ab_1
    - cython 3.0.11 py312h6891801_3
    - gettext 0.22.5 hdfe23c8_3
    - gettext-tools 0.22.5 hdfe23c8_3
    - icu 75.1 h120a0e1_0
    - ld64_osx-64 951.9 h38c89e5_1
    - ld64_osx-arm64 951.9 h2b3077e_1
    - libasprintf 0.22.5 hdfe23c8_3
    - libasprintf-devel 0.22.5 hdfe23c8_3
    - libclang-cpp17 17.0.6 default_hb173f14_7
    - libcxx 19.1.1 hf95d169_0
    - libcxx-devel 17.0.6 h8f8a49f_6
    - libexpat 2.6.3 hac325c4_0
    - libffi 3.4.2 h0d85af4_5
    - libgettextpo 0.22.5 hdfe23c8_3
    - libgettextpo-devel 0.22.5 hdfe23c8_3
    - libiconv 1.17 hd75f5a5_2
    - libintl 0.22.5 hdfe23c8_3
    - libintl-devel 0.22.5 hdfe23c8_3
    - libllvm17 17.0.6 hbedff68_1
    - libsqlite 3.46.1 h4b8f8c9_0
    - libxml2 2.12.7 heaf3512_4
    - libzlib 1.3.1 hd23fc13_2
    - llvm-tools 17.0.6 hbedff68_1
    - lz4-c 1.9.4 hf0c8a7f_0
    - macosx_deployment_target_osx-arm64 11.0 h6553868_1
    - ncurses 6.5 hf036a51_1
    - openssl 3.3.2 hd23fc13_0
    - popt 1.16 h7b079dc_2002
    - python 3.12.7 h8f8b54e_0_cpython
    - python_abi 3.12 5_cp312
    - readline 8.2 h9e318b2_1
    - rsync 3.3.0 h5aaac6a_0
    - sed 4.7 h3efe00b_1000
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1300.6.5 h390ca13_0
    - tk 8.6.13 h1abcd95_1
    - tzdata 2024b hc8b5060_0
    - xxhash 0.8.2 h4140336_0
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.6 h915ae27_0
  host:
    - bzip2 1.0.8 h99b78c6_7
    - ca-certificates 2024.8.30 hf0a4a13_0
    - cython 3.0.11 py312hde4cb15_2
    - libcxx 19.1.1 ha82da77_0
    - libexpat 2.6.3 hf9b8971_0
    - libffi 3.4.2 h3422bc3_5
    - libsqlite 3.46.1 hc14010f_0
    - libzlib 1.3.1 h8359307_2
    - ncurses 6.5 h7bae524_1
    - openssl 3.3.2 h8359307_0
    - pip 24.2 pyh8b19718_1
    - python 3.12.7 h739c21a_0_cpython
    - python_abi 3.12 5_cp312
    - readline 8.2 h92ec313_1
    - setuptools 75.1.0 pyhd8ed1ab_0
    - tk 8.6.13 h5083fa2_1
    - tzdata 2024b hc8b5060_0
    - wheel 0.44.0 pyhd8ed1ab_0
    - xz 5.2.6 h57fd34a_0
  run:
    - __osx >=11.0
    - python >=3.12,<3.13.0a0
    - python >=3.12,<3.13.0a0 *_cpython
    - python_abi 3.12.* *_cp312
test:
  commands:
    - python -c "from importlib.util import find_spec; assert find_spec('_ruamel_yaml')"
  downstreams:
    - ruamel.yaml
about:
  home: https://sourceforge.net/projects/ruamel-yaml-clib/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: C version of reader, parser and emitter for ruamel.yaml derived from libyaml
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20241012.1.1
  recipe-maintainers:
    - mbargull
    - ocefpaf
  remote_url: https://github.com/conda-forge/ruamel.yaml.clib-feedstock
  sha: d24d97d82ae0b570ff1935b9f3335bea4565c3b4
