# This file created by conda-build 24.7.1
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Wed Aug  7 16:01:37 2024
# ------------------------------------------------

package:
  name: fmt
  version: 11.0.2
source:
  sha256: 6cb1e6d37bdcb756dbbe59be438790db409cdb4868c66e888d5df9f13f7c027f
  url: https://github.com/fmtlib/fmt/archive/11.0.2.tar.gz
build:
  number: '0'
  run_exports:
    - fmt >=11.0.2,<12.0a0
  string: h420ef59_0
requirements:
  build:
    - bzip2 1.0.8 hfdf4475_7
    - c-ares 1.32.3 h51dda26_0
    - ca-certificates 2024.7.4 h8857fd0_0
    - cctools_osx-64 986 h303a5ab_3
    - cctools_osx-arm64 986 h458f0ca_3
    - clang 16.0.6 default_h179603d_11
    - clang-16 16.0.6 default_h0c94c6a_11
    - clang_impl_osx-arm64 16.0.6 ha81d56d_18
    - clang_osx-arm64 16.0.6 h40be2b1_18
    - clangxx 16.0.6 default_h179603d_11
    - clangxx_impl_osx-arm64 16.0.6 h4a79b72_18
    - clangxx_osx-arm64 16.0.6 h40be2b1_18
    - cmake 3.30.2 h749d262_0
    - compiler-rt 16.0.6 ha38d28d_2
    - compiler-rt_osx-64 16.0.6 ha38d28d_2
    - icu 75.1 h120a0e1_0
    - krb5 1.21.3 h37d8d59_0
    - ld64_osx-64 711 h04ffbf3_3
    - ld64_osx-arm64 711 ha337116_3
    - libclang-cpp16 16.0.6 default_h0c94c6a_11
    - libcurl 8.9.1 hfcf2730_0
    - libcxx 18.1.8 heced48a_2
    - libedit 3.1.20191231 h0678c8f_2
    - libev 4.33 h10d778d_2
    - libexpat 2.6.2 h73e2aa4_0
    - libiconv 1.17 hd75f5a5_2
    - libllvm16 16.0.6 hbedff68_3
    - libnghttp2 1.58.0 h64cf6d3_1
    - libssh2 1.11.0 hd019ec5_0
    - libuv 1.48.0 h67532ce_0
    - libxml2 2.12.7 heaf3512_4
    - libzlib 1.3.1 h87427d6_1
    - llvm-tools 16.0.6 hbedff68_3
    - macosx_deployment_target_osx-arm64 11.0 h6553868_1
    - make 4.3 h22f3db7_1
    - ncurses 6.5 h5846eda_0
    - openssl 3.3.1 h87427d6_2
    - rhash 1.4.4 h0dc2134_0
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.6 h915ae27_0
  host:
    - libcxx 18.1.8 h5a72898_2
  run:
    - __osx >=11.0
    - libcxx >=16
test:
  commands:
    - test -d ${PREFIX}/include/fmt
    - test -f ${PREFIX}/include/fmt/core.h
    - test -f ${PREFIX}/include/fmt/format.h
    - test -f ${PREFIX}/lib/cmake/fmt/fmt-config.cmake
    - test -f ${PREFIX}/lib/libfmt.dylib
  downstreams:
    - libmambapy
about:
  description: '{fmt} is an open-source formatting library for C++.

    It can be used as a safe and fast alternative to (s)printf and iostreams.

    '
  dev_url: https://github.com/fmtlib/fmt
  doc_url: https://fmt.dev/latest/
  home: https://fmt.dev/latest/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: '{fmt} is an open-source formatting library for C++'
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240807.1.1
  recipe-maintainers:
    - bdice
    - saraedum
    - tdegeus
    - vitaut
  remote_url: https://github.com/conda-forge/fmt-feedstock
  sha: aa512c06eed47ae7f0f9ef0178773d255e9055aa
