# This file created by conda-build 25.1.1
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Fri Jan 31 04:34:19 2025
# ------------------------------------------------

package:
  name: ca-certificates
  version: 2025.1.31
source:
  sha256: 3d5da6925056f6f18f119200434a4780a94263f10d1c21d032a6f6b2baa20651
  url: https://pypi.org/packages/source/c/certifi/certifi-2025.1.31.tar.gz
build:
  number: '0'
  string: hf0a4a13_0
requirements:
  build: []
  run: []
test:
  commands:
    - test -f "${PREFIX}/ssl/cacert.pem"
    - test -f "${PREFIX}/ssl/cert.pem"
    - curl --cacert "${PREFIX}/ssl/cacert.pem" https://www.google.com
  requires:
    - curl
about:
  home: https://github.com/conda-forge/ca-certificates-feedstock
  license: ISC
  license_file: LICENSE
  summary: Certificates for use with other packages.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20250130.2.1
  recipe-maintainers:
    - jakirkham
    - msarahan
    - mwcraig
    - ocefpaf
    - patricksnape
    - pelson
    - scopatz
  remote_url: https://github.com/conda-forge/ca-certificates-feedstock
  sha: d13d63b3192ec707b514637930fd215d0776c604
