CONDA_BUILD_SYSROOT: /Applications/Xcode_15.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk
MACOSX_DEPLOYMENT_TARGET: '11.0'
c_compiler: clang
c_compiler_version: '18'
c_stdlib: macosx_deployment_target
c_stdlib_version: '11.0'
channel_targets: conda-forge main
ncurses: '6'
perl: 5.32.1
target_platform: osx-arm64
